BEGIN;

DROP SCHEMA IF EXISTS public CASCADE;
CREATE SCHEMA public;

GRANT USAGE ON SCHEMA public TO postgres, anon, authenticated, service_role;
GRANT ALL   ON SCHEMA public TO postgres;

COMMIT;

CREATE TABLE IF NOT EXISTS public."CloudflaredEndpoints"
(
  "Id"          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Name"        text   NOT NULL,
  "PublicUrl"   text   NOT NULL,
  "LocalTarget" text   NULL,
  "Note"        text   NULL,
  "CreatedAt"   timestamptz NOT NULL DEFAULT now(),
  "UpdatedAt"   timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS "UX_CloudflaredEndpoints_Name"
ON public."CloudflaredEndpoints" ("Name");

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW."UpdatedAt" = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS "TR_CloudflaredEndpoints_UpdatedAt" ON public."CloudflaredEndpoints";
CREATE TRIGGER "TR_CloudflaredEndpoints_UpdatedAt"
BEFORE UPDATE ON public."CloudflaredEndpoints"
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();
