// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using TunnelBackend.Features.Entities;

namespace TunnelBackend.Data;

public partial class AppDbContext : DbContext
{
    public AppDbContext(DbContextOptions<AppDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Crm_BillcoListtab> Crm_BillcoListtab { get; set; }

    public virtual DbSet<Crm_BillcoMaintab> Crm_BillcoMaintab { get; set; }

    public virtual DbSet<P_EmployeeTab> P_EmployeeTab { get; set; }

    public virtual DbSet<Sys_FileRecord> Sys_FileRecord { get; set; }

    public virtual DbSet<mes_ProcessListTab> mes_ProcessListTab { get; set; }

    public virtual DbSet<mes_ProcessTab> mes_ProcessTab { get; set; }

    public virtual DbSet<mes_fl_listtab> mes_fl_listtab { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Crm_BillcoListtab>(entity =>
        {
            entity.ToTable(tb =>
                {
                    tb.HasComment("销售订单明细表");
                    tb.HasTrigger("trg_Crm_BillcoListtab_AfterUpdate");
                    tb.HasTrigger("trg_crm_billcolisttab_update");
                });

            entity.Property(e => e.badamount)
                .HasDefaultValue(0)
                .HasAnnotation("Relational:DefaultConstraintName", "DF__Crm_Billc__badam__29B02593");
            entity.Property(e => e.crm_Lco_price1)
                .HasDefaultValue(0m)
                .HasComment("预留价格1")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoListtab_crm_lco_price1");
            entity.Property(e => e.crm_Lco_price2)
                .HasDefaultValue(0m)
                .HasComment("预留价格2")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoListtab_crm_lco_price2");
            entity.Property(e => e.crm_Lco_price3)
                .HasDefaultValue(0m)
                .HasComment("预留价格3")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoListtab_crm_lco_price3");
            entity.Property(e => e.crm_Lco_price4)
                .HasDefaultValue(0m)
                .HasComment("预留价格4")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoListtab_crm_lco_price4");
            entity.Property(e => e.crm_Lco_price5)
                .HasDefaultValue(0m)
                .HasComment("预留价格5")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoListtab_crm_lco_price5");
            entity.Property(e => e.crm_lco_DJmaxamount)
                .HasDefaultValue(0m)
                .HasAnnotation("Relational:DefaultConstraintName", "DF__Crm_Billc__crm_l__045EA553");
            entity.Property(e => e.crm_lco_DJminamount)
                .HasDefaultValue(0m)
                .HasAnnotation("Relational:DefaultConstraintName", "DF__Crm_Billc__crm_l__036A811A");
            entity.Property(e => e.crm_lco_DJpirce)
                .HasDefaultValue(0m)
                .HasAnnotation("Relational:DefaultConstraintName", "DF__Crm_Billc__crm_l__0A177EA9");
            entity.Property(e => e.crm_lco_DyTig)
                .HasDefaultValue(0)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoListtab_crm_lco_DyTig");
            entity.Property(e => e.crm_lco_Orderminamount)
                .HasDefaultValue(0m)
                .HasAnnotation("Relational:DefaultConstraintName", "DF__Crm_Billc__crm_l__0552C98C");
            entity.Property(e => e.crm_lco_amount)
                .HasDefaultValue(0m)
                .HasComment("数量")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoListtab_crm_lco_amount");
            entity.Property(e => e.crm_lco_anotherbak)
                .HasDefaultValue("")
                .HasComment("其它要求")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__Crm_Billc__crm_l__70204077");
            entity.Property(e => e.crm_lco_appellation)
                .HasDefaultValue("")
                .HasComment("产品名称")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoListtab_crm_lco_appellation");
            entity.Property(e => e.crm_lco_bak)
                .HasDefaultValue("")
                .HasComment("明细备注")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoListtab_crm_lco_bak");
            entity.Property(e => e.crm_lco_billdocument_id)
                .HasDefaultValue("")
                .HasComment("单据编号")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoListtab_crm_lco_billdocument_id");
            entity.Property(e => e.crm_lco_bprice)
                .HasDefaultValue(0m)
                .HasComment("成本单价")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoListtab_crm_lco_bprice");
            entity.Property(e => e.crm_lco_brand).HasComment("品牌");
            entity.Property(e => e.crm_lco_bsummoney)
                .HasDefaultValue(0m)
                .HasComment("成本金额")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoListtab_crm_lco_bsummoney");
            entity.Property(e => e.crm_lco_buytime)
                .HasDefaultValueSql("(getdate())")
                .HasComment("要货时间")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoListtab_crm_lco_buytime");
            entity.Property(e => e.crm_lco_cdbillno).HasComment("传递生成后的单据号");
            entity.Property(e => e.crm_lco_cdop).HasComment("传递操作人");
            entity.Property(e => e.crm_lco_cdproductid).HasComment("传递的物料编码");
            entity.Property(e => e.crm_lco_clientid).HasComment("结算客户");
            entity.Property(e => e.crm_lco_comid)
                .HasDefaultValue(0)
                .HasComment("发货完成")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoListtab_crm_lco_comid");
            entity.Property(e => e.crm_lco_comid_bom)
                .HasDefaultValue(0)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoListtab_crm_lco_comid_bom");
            entity.Property(e => e.crm_lco_comidname)
                .HasDefaultValue("")
                .HasComment("发货完成人员")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoListtab_crm_lco_comidname");
            entity.Property(e => e.crm_lco_crmplanid)
                .HasDefaultValue(0)
                .HasComment("销售计划")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoListtab_crm_lco_crmplanid");
            entity.Property(e => e.crm_lco_exchangeRate)
                .HasDefaultValue(0m)
                .HasComment("汇率")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoListtab_crm_lco_exchangeRate");
            entity.Property(e => e.crm_lco_expectid).HasComment("预计实现ID");
            entity.Property(e => e.crm_lco_famount)
                .HasDefaultValue(0m)
                .HasComment("辅助数量")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoListtab_crm_lco_famount");
            entity.Property(e => e.crm_lco_finish)
                .HasDefaultValue(0)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoListtab_crm_lco_finish");
            entity.Property(e => e.crm_lco_finishAmount)
                .HasDefaultValue(0m)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoListtab_crm_lco_finishAmount");
            entity.Property(e => e.crm_lco_gqTig).HasDefaultValue(0);
            entity.Property(e => e.crm_lco_gqop).HasDefaultValue("");
            entity.Property(e => e.crm_lco_guidstr).HasDefaultValueSql("(newid())");
            entity.Property(e => e.crm_lco_itemno)
                .HasDefaultValue("")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__Crm_Billc__crm_l__645B8252");
            entity.Property(e => e.crm_lco_jcomid)
                .HasDefaultValue(0)
                .HasComment("入库完成")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__Crm_Billc__crm_l__2FD0B138");
            entity.Property(e => e.crm_lco_jcomidname)
                .HasDefaultValue("")
                .HasComment("入库完成人员")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoListtab_crm_lco_jcomidname");
            entity.Property(e => e.crm_lco_jdtag)
                .HasDefaultValue("")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__Crm_Billc__crm_l__45E4B1F2");
            entity.Property(e => e.crm_lco_jhtig)
                .HasDefaultValue(0)
                .HasAnnotation("Relational:DefaultConstraintName", "DF__Crm_Billc__crm_l__06468602");
            entity.Property(e => e.crm_lco_kcamount)
                .HasDefaultValue(0m)
                .HasComment("仓库分解")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoListtab_crm_lco_wmamount2");
            entity.Property(e => e.crm_lco_kyamount)
                .HasDefaultValue(0m)
                .HasComment("仓库分解")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoListtab_crm_lco_wmamount1");
            entity.Property(e => e.crm_lco_labelbak)
                .HasDefaultValue("")
                .HasComment("标签要求")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoListtab_crm_lco_labelbak");
            entity.Property(e => e.crm_lco_lpoid)
                .HasDefaultValue(0)
                .HasAnnotation("Relational:DefaultConstraintName", "DF__Crm_Billc__crm_l__7180DB09");
            entity.Property(e => e.crm_lco_model)
                .HasDefaultValueSql("((0))")
                .HasComment("产品规格")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoListtab_crm_lco_model");
            entity.Property(e => e.crm_lco_modifyid)
                .HasDefaultValue(0)
                .HasComment("修改id")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__Crm_Billc__crm_l__7FE4D450");
            entity.Property(e => e.crm_lco_mrpFXID)
                .HasDefaultValue(0)
                .HasAnnotation("Relational:DefaultConstraintName", "DF__Crm_Billc__crm_l__54B94C0F");
            entity.Property(e => e.crm_lco_mrpamount)
                .HasDefaultValue(0m)
                .HasComment("自产分解")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoListtab_crm_lco_mrpamount");
            entity.Property(e => e.crm_lco_noprice)
                .HasDefaultValue(0m)
                .HasComment("不含税单价")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoListtab_crm_lco_noprice");
            entity.Property(e => e.crm_lco_nosummoney)
                .HasDefaultValue(0m)
                .HasComment("不含税金额")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoListtab_crm_lco_nosummoney");
            entity.Property(e => e.crm_lco_packingbak)
                .HasDefaultValue("")
                .HasComment("包装要求")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoListtab_crm_lco_packingbak");
            entity.Property(e => e.crm_lco_planamount).HasComment("预排数量");
            entity.Property(e => e.crm_lco_planbak).HasComment("分解说明");
            entity.Property(e => e.crm_lco_plancomid)
                .HasDefaultValue(0)
                .HasAnnotation("Relational:DefaultConstraintName", "DF__Crm_Billc__crm_l__397EDB0D");
            entity.Property(e => e.crm_lco_plancomoper)
                .HasDefaultValue("")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__Crm_Billc__crm_l__3A72FF46");
            entity.Property(e => e.crm_lco_planid)
                .HasDefaultValue(0)
                .HasAnnotation("Relational:DefaultConstraintName", "DF__Crm_Billc__plani__6F196FAA");
            entity.Property(e => e.crm_lco_price)
                .HasDefaultValue(0m)
                .HasComment("单价")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoListtab_crm_lco_price");
            entity.Property(e => e.crm_lco_productdescrip).HasComment("综合属性");
            entity.Property(e => e.crm_lco_productid)
                .HasDefaultValue("")
                .HasComment("物料编码")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoListtab_crm_lco_productid");
            entity.Property(e => e.crm_lco_productunit)
                .HasDefaultValue("")
                .HasComment("产品单位")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoListtab_crm_lco_productunit");
            entity.Property(e => e.crm_lco_project_manager).HasComment("项目经理");
            entity.Property(e => e.crm_lco_receiveunit).HasComment("接收单位");
            entity.Property(e => e.crm_lco_scmamount)
                .HasDefaultValue(0m)
                .HasComment("外购分解")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoListtab_crm_lco_scmamount");
            entity.Property(e => e.crm_lco_shclientid)
                .HasDefaultValue(0)
                .HasComment("发货客户")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoListtab_crm_lco_ocustomerid");
            entity.Property(e => e.crm_lco_snmark)
                .HasDefaultValue("")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__Crm_Billc__wms_l__56D63B17");
            entity.Property(e => e.crm_lco_sourcebillid)
                .HasDefaultValue("")
                .HasComment("原单编号")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoListtab_crm_lco_sourcebillid");
            entity.Property(e => e.crm_lco_sourcename)
                .HasDefaultValue("")
                .HasComment("原单名称")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoListtab_crm_lco_sourcename");
            entity.Property(e => e.crm_lco_spec)
                .HasDefaultValueSql("((0))")
                .HasComment("产品型号")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoListtab_crm_lco_spec");
            entity.Property(e => e.crm_lco_storage)
                .HasDefaultValue(0m)
                .HasComment("仓量库数")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__Crm_Billc__crm_l__74E4F594");
            entity.Property(e => e.crm_lco_storageZd)
                .HasDefaultValue(0m)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoListtab_crm_lco_storageZd");
            entity.Property(e => e.crm_lco_str1)
                .HasDefaultValue("")
                .HasComment("自定2")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoListtab_crm_lco_str1");
            entity.Property(e => e.crm_lco_str10).HasComment("自定义10");
            entity.Property(e => e.crm_lco_str11).HasComment("自定义11");
            entity.Property(e => e.crm_lco_str12).HasComment("自定义12");
            entity.Property(e => e.crm_lco_str2)
                .HasDefaultValue("")
                .HasComment("自定3")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoListtab_crm_lco_str2");
            entity.Property(e => e.crm_lco_str6).HasComment("自定义6");
            entity.Property(e => e.crm_lco_str7).HasComment("自定义7");
            entity.Property(e => e.crm_lco_str8).HasComment("自定义8");
            entity.Property(e => e.crm_lco_str9).HasComment("自定义9");
            entity.Property(e => e.crm_lco_summoney)
                .HasDefaultValue(0m)
                .HasComment("金额")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoListtab_crm_lco_summoney");
            entity.Property(e => e.crm_lco_taxRate)
                .HasDefaultValue(0m)
                .HasComment("税率")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoListtab_crm_lco_taxRate");
            entity.Property(e => e.crm_lco_taxsummoney)
                .HasDefaultValue(0m)
                .HasComment("税额")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoListtab_crm_lco_taxsummoney");
            entity.Property(e => e.crm_lco_technicalbak)
                .HasDefaultValue("")
                .HasComment("技术要求")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoListtab_crm_lco_technicalbak");
            entity.Property(e => e.crm_lco_tm)
                .HasDefaultValue("")
                .HasComment("订单条码")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoListtab_crm_lco_tm");
            entity.Property(e => e.crm_lco_waitnotice)
                .HasDefaultValue(0)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoListtab_crm_lco_waitnotice");
            entity.Property(e => e.crm_lco_wmamount)
                .HasDefaultValue(0m)
                .HasComment("仓库分解")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoListtab_crm_lco_wmamount");
            entity.Property(e => e.crm_lco_wwamount)
                .HasDefaultValue(0m)
                .HasComment("委外分解")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoListtab_crm_lco_wwamount");
            entity.Property(e => e.crm_lco_yftig).HasDefaultValue(0);
            entity.Property(e => e.longamount)
                .HasDefaultValue(0)
                .HasAnnotation("Relational:DefaultConstraintName", "DF__Crm_Billc__longa__28BC015A");
        });

        modelBuilder.Entity<Crm_BillcoMaintab>(entity =>
        {
            entity.ToTable(tb => tb.HasComment("销售订单主表"));

            entity.Property(e => e.crm_mco_billdocument_id)
                .HasDefaultValueSql("((0))")
                .HasComment("单据编号")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoMaintab_crm_mco_billdocument_id");
            entity.Property(e => e.crm_mco_AffirmDate).HasComment("提交时间");
            entity.Property(e => e.crm_mco_Affirmer)
                .HasDefaultValue(0)
                .HasComment("提交人")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoMaintab_crm_mco_Affirmer");
            entity.Property(e => e.crm_mco_LockTig)
                .HasDefaultValue(0)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoMaintab_crm_mco_LockTig");
            entity.Property(e => e.crm_mco_Related).HasComment("相关单号");
            entity.Property(e => e.crm_mco_Transport)
                .HasDefaultValue("")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__Crm_Billc__crm_m__0A45948E");
            entity.Property(e => e.crm_mco_URGENT)
                .HasDefaultValue("否")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__Crm_Billc__crm_m__64B0EFD0");
            entity.Property(e => e.crm_mco_address)
                .HasDefaultValue("")
                .HasComment("送货地址")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoMaintab_crm_mco_address");
            entity.Property(e => e.crm_mco_automsgenddt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("提醒时间")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoMaintab_crm_mco_automsgenddt");
            entity.Property(e => e.crm_mco_automsgsign)
                .HasDefaultValue(0)
                .HasComment("提醒标识")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoMaintab_crm_mco_automsgsign");
            entity.Property(e => e.crm_mco_bak)
                .HasDefaultValue("")
                .HasComment("主单备注")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoMaintab_crm_mco_bak");
            entity.Property(e => e.crm_mco_ban)
                .HasDefaultValue(0)
                .HasComment("审批锁定")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoMaintab_crm_mco_ban");
            entity.Property(e => e.crm_mco_billtype)
                .HasDefaultValue(0)
                .HasComment("流转类别")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoMaintab_crm_mco_billtype");
            entity.Property(e => e.crm_mco_cancelFlag)
                .HasDefaultValue(0)
                .HasComment("关闭标记")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoMaintab_crm_mco_cancelFlag");
            entity.Property(e => e.crm_mco_cancelOper).HasComment("关闭人员");
            entity.Property(e => e.crm_mco_cancelTime).HasComment("关闭时间");
            entity.Property(e => e.crm_mco_cdbillno).HasComment("传递生成后的单据号");
            entity.Property(e => e.crm_mco_cdop).HasComment("传递操作人");
            entity.Property(e => e.crm_mco_cdzt).HasComment("传递账套");
            entity.Property(e => e.crm_mco_changedt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("变更时间")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoMaintab_crm_mco_changedt");
            entity.Property(e => e.crm_mco_changeid)
                .HasDefaultValue(0)
                .HasComment("变更人员")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoMaintab_crm_mco_changeid");
            entity.Property(e => e.crm_mco_clientid)
                .HasDefaultValue(0)
                .HasComment("结算客户")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoMaintab_crm_mco_clientid");
            entity.Property(e => e.crm_mco_cn)
                .HasDefaultValue(1)
                .HasAnnotation("Relational:DefaultConstraintName", "DF__Crm_Billc__crm_m__726BA8F8");
            entity.Property(e => e.crm_mco_colorid)
                .HasDefaultValue("")
                .HasComment("颜色标识")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoMaintab_crm_mco_colorid");
            entity.Property(e => e.crm_mco_complete).HasComment("准备完成时间");
            entity.Property(e => e.crm_mco_contractno).HasComment("合同号");
            entity.Property(e => e.crm_mco_currency)
                .HasDefaultValue(0)
                .HasComment("货币单位")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__Crm_Billc__crm_m__5E01903C");
            entity.Property(e => e.crm_mco_currencytype).HasComment("货币类型");
            entity.Property(e => e.crm_mco_date1).HasComment("预留日期1");
            entity.Property(e => e.crm_mco_date2).HasComment("预留日期2");
            entity.Property(e => e.crm_mco_date3).HasComment("预留日期3");
            entity.Property(e => e.crm_mco_date4).HasComment("预留日期4");
            entity.Property(e => e.crm_mco_date5).HasComment("预留日期5");
            entity.Property(e => e.crm_mco_date6).HasComment("预留日期6");
            entity.Property(e => e.crm_mco_date7).HasComment("预留日期7");
            entity.Property(e => e.crm_mco_delbak)
                .HasDefaultValue("")
                .HasComment("禁用说明")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoMaintab_crm_mco_delbak");
            entity.Property(e => e.crm_mco_deldt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("禁用时间")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoMaintab_crm_mco_deldt");
            entity.Property(e => e.crm_mco_delid)
                .HasDefaultValue(0)
                .HasComment("禁用标记")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoMaintab_crm_mco_delid");
            entity.Property(e => e.crm_mco_delivery)
                .HasDefaultValueSql("('')")
                .HasComment("发货方式")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoMaintab_crm_mco_delivery");
            entity.Property(e => e.crm_mco_deloperatorid)
                .HasDefaultValue(0)
                .HasComment("删除人员")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoMaintab_crm_mco_deloperatorid");
            entity.Property(e => e.crm_mco_endtime).HasComment("结束时间");
            entity.Property(e => e.crm_mco_groupid)
                .HasDefaultValue(0)
                .HasAnnotation("Relational:DefaultConstraintName", "DF__Crm_Billc__crm_m__09517055");
            entity.Property(e => e.crm_mco_handcraftId)
                .HasDefaultValueSql("((0))")
                .HasComment("手工单号")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoMaintab_crm_mco_handcraftId");
            entity.Property(e => e.crm_mco_happentime).HasComment("发生时间");
            entity.Property(e => e.crm_mco_id).ValueGeneratedOnAdd();
            entity.Property(e => e.crm_mco_inoutspecies)
                .HasDefaultValue(0)
                .HasComment("单据类别")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoMaintab_crm_mco_inoutspecies");
            entity.Property(e => e.crm_mco_int1)
                .HasDefaultValue(0)
                .HasComment("预留整型字段1")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__Crm_Billc__crm_m__00E57C2F");
            entity.Property(e => e.crm_mco_int2)
                .HasDefaultValue(0)
                .HasComment("预留整型字段2")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__Crm_Billc__crm_m__01D9A068");
            entity.Property(e => e.crm_mco_itemname).HasComment("项目名称");
            entity.Property(e => e.crm_mco_itemno).HasComment("项目编号");
            entity.Property(e => e.crm_mco_jiajitig)
                .HasDefaultValue(0)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoMaintab_crm_mco_jiajitig");
            entity.Property(e => e.crm_mco_linkman)
                .HasDefaultValue("")
                .HasComment("联系人员")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoMaintab_crm_mco_linkman");
            entity.Property(e => e.crm_mco_mcomid)
                .HasDefaultValue(0)
                .HasComment("整单完成")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoMaintab_crm_mco_mcomid");
            entity.Property(e => e.crm_mco_operatedate)
                .HasDefaultValueSql("(getdate())")
                .HasComment("操作时间")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoMaintab_crm_mco_operatedate");
            entity.Property(e => e.crm_mco_operatorid)
                .HasDefaultValue(0)
                .HasComment("操作员ID")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoMaintab_crm_mco_operatorid");
            entity.Property(e => e.crm_mco_operatorname)
                .HasDefaultValue("")
                .HasComment("操作员名称")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoMaintab_crm_mco_operatorname");
            entity.Property(e => e.crm_mco_pStepCode).HasComment("已审步骤");
            entity.Property(e => e.crm_mco_payment)
                .HasDefaultValue(0)
                .HasComment("付款方式")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoMaintab_crm_mco_payment");
            entity.Property(e => e.crm_mco_phone)
                .HasDefaultValue("")
                .HasComment("联系电话")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoMaintab_crm_mco_phone");
            entity.Property(e => e.crm_mco_pidtypeid)
                .HasDefaultValue(0)
                .HasComment("产品类别")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__Crm_Billc__crm_m__5EF5B475");
            entity.Property(e => e.crm_mco_previewCount)
                .HasDefaultValue(0)
                .HasComment("预览次数")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoMaintab_crm_mco_previewCount");
            entity.Property(e => e.crm_mco_previewLastOper).HasComment("最后预览人员");
            entity.Property(e => e.crm_mco_previewLastTime).HasComment("最后预览时间");
            entity.Property(e => e.crm_mco_printCount)
                .HasDefaultValue(0)
                .HasComment("打印次数")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoMaintab_crm_mco_printCount");
            entity.Property(e => e.crm_mco_printLastOper).HasComment("最后打印人员");
            entity.Property(e => e.crm_mco_printLastTime).HasComment("最后打印时间");
            entity.Property(e => e.crm_mco_projectNo).HasDefaultValue("");
            entity.Property(e => e.crm_mco_requirements).HasComment("开票要求");
            entity.Property(e => e.crm_mco_rtagid)
                .HasDefaultValue(0)
                .HasComment("单据标识")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoMaintab_crm_mco_rtagid");
            entity.Property(e => e.crm_mco_seller)
                .HasDefaultValue("")
                .HasComment("销售人员")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoMaintab_crm_mco_seller");
            entity.Property(e => e.crm_mco_settlementdays)
                .HasDefaultValueSql("((0))")
                .HasComment("初始结算周期")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoMaintab_crm_mco_settlementdays");
            entity.Property(e => e.crm_mco_shclientid)
                .HasDefaultValue(0)
                .HasComment("发货客户")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoMaintab_crm_mco_ocustomerid");
            entity.Property(e => e.crm_mco_snmark).HasComment("图号");
            entity.Property(e => e.crm_mco_stepOverName).HasComment("终审人员");
            entity.Property(e => e.crm_mco_stepTime)
                .HasDefaultValue(0m)
                .HasComment("处理时限")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoMaintab_crm_mco_stepTime");
            entity.Property(e => e.crm_mco_stepcode)
                .HasDefaultValue(0)
                .HasComment("步骤代码")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoMaintab_crm_mco_stepcode");
            entity.Property(e => e.crm_mco_stepdirection)
                .IsFixedLength()
                .HasComment("流转方向");
            entity.Property(e => e.crm_mco_stepover)
                .HasDefaultValue(0)
                .HasComment("终审标记")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoMaintab_crm_mco_stepover");
            entity.Property(e => e.crm_mco_stepoverid)
                .HasDefaultValue(0)
                .HasComment("终审人ID")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoMaintab_crm_mco_stepoverid");
            entity.Property(e => e.crm_mco_stepovertime).HasComment("终审时间");
            entity.Property(e => e.crm_mco_str1).HasComment("预留字符串1");
            entity.Property(e => e.crm_mco_str2).HasComment("预留字符串2");
            entity.Property(e => e.crm_mco_str3).HasComment("预留字符串3");
            entity.Property(e => e.crm_mco_str4).HasComment("预留字符串4");
            entity.Property(e => e.crm_mco_str5)
                .HasDefaultValue("")
                .HasComment("预留字符串5")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoMaintab_crm_mco_str5");
            entity.Property(e => e.crm_mco_str6)
                .HasDefaultValue("")
                .HasComment("预留字符串6")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoMaintab_crm_mco_str6");
            entity.Property(e => e.crm_mco_str7)
                .HasDefaultValue("")
                .HasComment("预留字符串7")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoMaintab_crm_mco_str7");
            entity.Property(e => e.crm_mco_tagid)
                .HasDefaultValue(0)
                .HasComment("订单类型")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Crm_BillcoMaintab_crm_mco_tagid");
            entity.Property(e => e.divide_bill).HasDefaultValue("");
        });

        modelBuilder.Entity<P_EmployeeTab>(entity =>
        {
            entity.ToTable(tb => tb.HasComment("员工表"));

            entity.Property(e => e.employeeid)
                .ValueGeneratedNever()
                .HasComment("人员ID");
            entity.Property(e => e.AffirmPurview)
                .HasDefaultValue("")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_P_EmployeeTab_AffirmPurview");
            entity.Property(e => e.AuditPurview)
                .HasDefaultValue("")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_P_EmployeeTab_AuditPurview");
            entity.Property(e => e.DD).IsFixedLength();
            entity.Property(e => e.DeletePurview)
                .HasDefaultValue("")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_P_EmployeeTab_DeletePurview");
            entity.Property(e => e.Departmentid)
                .HasDefaultValue(0)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_P_EmployeeTab_Departmentid");
            entity.Property(e => e.DepotPurview)
                .HasDefaultValue("")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_P_EmployeeTab_DepotPurview");
            entity.Property(e => e.DirectSuperior)
                .HasDefaultValue("")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_P_EmployeeTab_DirectSuperior");
            entity.Property(e => e.DutyInt)
                .HasDefaultValueSql("((0))")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_P_EmployeeTab_DutyInt");
            entity.Property(e => e.FieldServiceType)
                .HasDefaultValue(1)
                .HasAnnotation("Relational:DefaultConstraintName", "DF__P_Employe__Field__621BD220");
            entity.Property(e => e.LoginAccount)
                .HasDefaultValue("")
                .HasComment("员工工号")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_P_EmployeeTab_LoginAccount");
            entity.Property(e => e.P_emp_nzjBs).HasComment("年终奖倍数");
            entity.Property(e => e.P_emp_nzjRzDate).HasComment("非实习入职日期");
            entity.Property(e => e.P_emp_offerXz).HasComment("offer薪资");
            entity.Property(e => e.Password)
                .HasDefaultValue("E0B97F132980BB0856ECC51BA256626F3CB68D11")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_P_EmployeeTab_Password");
            entity.Property(e => e.Purview)
                .HasDefaultValue("")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_P_EmployeeTab_Purview");
            entity.Property(e => e.SoftOpenMode)
                .HasDefaultValue((short)0)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_P_EmployeeTab_SoftOpenMode");
            entity.Property(e => e.SpeciesNo)
                .HasDefaultValue("01")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_P_EmployeeTab_SpeciesNo");
            entity.Property(e => e.SyncFlag)
                .HasDefaultValue(0)
                .HasAnnotation("Relational:DefaultConstraintName", "DF__P_Employe__SyncF__14B3A3C9");
            entity.Property(e => e.UseFlag)
                .HasDefaultValue(0)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_P_EmployeeTab_UseFlag");
            entity.Property(e => e.UseFlag1)
                .HasDefaultValue(0)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_P_EmployeeTab_UseFlag1");
            entity.Property(e => e.WgAmount)
                .HasDefaultValue(0)
                .HasAnnotation("Relational:DefaultConstraintName", "DF__P_Employe__WgAmo__65F1270E");
            entity.Property(e => e.Xzclass)
                .HasDefaultValue(0)
                .HasAnnotation("Relational:DefaultConstraintName", "DF__P_Employe__Xzcla__6314BA63");
            entity.Property(e => e.lookmsgid).HasAnnotation("Relational:DefaultConstraintName", "DF__P_Employe__lookm__5B25555B");
            entity.Property(e => e.lskjimport_errorFlag)
                .HasDefaultValue("0")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__P_Employe__lskji__4BF4597B");
            entity.Property(e => e.msgdt)
                .HasDefaultValue(300)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_P_EmployeeTab_msgdt");
            entity.Property(e => e.msglookid).HasAnnotation("Relational:DefaultConstraintName", "DF__P_Employe__msglo__169BEC3B");
            entity.Property(e => e.p_emp_AffirmDate).HasComment("提交时间");
            entity.Property(e => e.p_emp_Affirmer)
                .HasDefaultValue(0)
                .HasComment("提交人")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_P_EmployeeTab_p_emp_Affirmer");
            entity.Property(e => e.p_emp_CarTig)
                .HasDefaultValue(0)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_P_EmployeeTab_p_emp_CarTig");
            entity.Property(e => e.p_emp_DisabilityTig)
                .HasDefaultValue(0)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_P_EmployeeTab_p_emp_DisabilityTig");
            entity.Property(e => e.p_emp_FinanceType).HasComment("财务分类");
            entity.Property(e => e.p_emp_Remark).HasComment("人员备注");
            entity.Property(e => e.p_emp_ResidenceType).HasComment("户口类型");
            entity.Property(e => e.p_emp_Rtagid)
                .HasDefaultValue(0)
                .HasComment("红蓝字单据")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_P_EmployeeTab_p_emp_Rtagid");
            entity.Property(e => e.p_emp_SecretAgreement).HasComment("保密协议");
            entity.Property(e => e.p_emp_address)
                .HasDefaultValue("")
                .HasComment("现居地址")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_P_EmployeeTab_p_emp_address");
            entity.Property(e => e.p_emp_area)
                .HasDefaultValue("考勤区域")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__P_Employe__p_emp__13BF7F90");
            entity.Property(e => e.p_emp_areaid)
                .HasDefaultValueSql("((0))")
                .HasComment("区域")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_P_EmployeeTab_p_emp_areaid");
            entity.Property(e => e.p_emp_automsgenddt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("提醒时间")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_P_EmployeeTab_p_emp_automsgenddt");
            entity.Property(e => e.p_emp_automsgsign)
                .HasDefaultValue(0)
                .HasComment("提醒标识")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_P_EmployeeTab_p_emp_automsgsign");
            entity.Property(e => e.p_emp_ban)
                .HasDefaultValue(0)
                .HasComment("审批锁定")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_P_EmployeeTab_p_emp_ban");
            entity.Property(e => e.p_emp_basesalary)
                .HasDefaultValue(0.0)
                .HasComment("基本工资")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_P_EmployeeTab_p_emp_basesalary");
            entity.Property(e => e.p_emp_billtype)
                .HasDefaultValue(0)
                .HasComment("流转类别")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_P_EmployeeTab_p_emp_billtype");
            entity.Property(e => e.p_emp_birthday).HasComment("出生日期\r\n");
            entity.Property(e => e.p_emp_businessadddt).HasComment("商业险增加日期\r\n");
            entity.Property(e => e.p_emp_businessage)
                .HasDefaultValue(0.0)
                .HasComment("企业工龄")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_P_EmployeeTab_p_emp_businessage");
            entity.Property(e => e.p_emp_businesstype)
                .HasDefaultValue("")
                .HasComment("商业险类型")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_P_EmployeeTab_p_emp_businesstype");
            entity.Property(e => e.p_emp_businessway)
                .HasDefaultValue("")
                .HasComment("商业险增加方式")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_P_EmployeeTab_p_emp_businessway");
            entity.Property(e => e.p_emp_changedt).HasComment("变更时间");
            entity.Property(e => e.p_emp_changeid)
                .HasDefaultValue(0)
                .HasComment("变更人员ID")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_P_EmployeeTab_p_emp_changeid");
            entity.Property(e => e.p_emp_colorid)
                .HasDefaultValue("")
                .HasComment("颜色标识")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_P_EmployeeTab_p_emp_colorid");
            entity.Property(e => e.p_emp_contractcount)
                .HasDefaultValueSql("((0))")
                .HasComment("第几次签订合同")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_P_EmployeeTab_p_emp_contractcount");
            entity.Property(e => e.p_emp_contractendbak)
                .HasDefaultValue("")
                .HasComment("离职原因\r\n")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_P_EmployeeTab_p_emp_contractendbak");
            entity.Property(e => e.p_emp_contractendcontent)
                .HasDefaultValue("")
                .HasComment("被动离职的具体原因")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_P_EmployeeTab_p_emp_contractendcontent");
            entity.Property(e => e.p_emp_contractenddt).HasComment("离退休时间\r\n");
            entity.Property(e => e.p_emp_contractno)
                .HasDefaultValue("正式员工")
                .HasComment("目前执行合同编号")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_P_EmployeeTab_p_emp_contractno");
            entity.Property(e => e.p_emp_contractplanedt).HasComment("劳动合同止时间\r\n");
            entity.Property(e => e.p_emp_contractsdt).HasComment("劳动合同起时间");
            entity.Property(e => e.p_emp_contracttype)
                .HasDefaultValue("")
                .HasComment("合同类型")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_P_EmployeeTab_p_emp_contracttype");
            entity.Property(e => e.p_emp_degree)
                .HasDefaultValue("")
                .HasComment("学历")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_P_EmployeeTab_p_emp_degree");
            entity.Property(e => e.p_emp_delbak)
                .HasDefaultValue("")
                .HasComment("禁用说明")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_P_EmployeeTab_p_emp_delbak");
            entity.Property(e => e.p_emp_deldt).HasComment("禁用时间");
            entity.Property(e => e.p_emp_delid)
                .HasDefaultValue(0)
                .HasComment("禁用标识")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_P_EmployeeTab_p_emp_delid");
            entity.Property(e => e.p_emp_deloperatorid).HasComment("删除人员");
            entity.Property(e => e.p_emp_duty)
                .HasDefaultValue("")
                .HasComment("专业技术职务")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_P_EmployeeTab_p_emp_duty");
            entity.Property(e => e.p_emp_email)
                .HasDefaultValue("")
                .HasComment("邮箱地址\r\n")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_P_EmployeeTab_p_emp_email");
            entity.Property(e => e.p_emp_endtime).HasComment("结束时间");
            entity.Property(e => e.p_emp_endworkdt).HasComment("最后工作日");
            entity.Property(e => e.p_emp_fax)
                .HasDefaultValue("")
                .HasComment("联系传真\r\n")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_P_EmployeeTab_p_emp_fax");
            entity.Property(e => e.p_emp_fundadddt)
                .HasDefaultValueSql("('')")
                .HasComment("公积金增加日期\r\n")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_P_EmployeeTab_p_emp_fundadddt");
            entity.Property(e => e.p_emp_fundnum)
                .HasDefaultValue("")
                .HasComment("公积金个人编号")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_P_EmployeeTab_p_emp_fundnum");
            entity.Property(e => e.p_emp_graduatedschool)
                .HasDefaultValue("")
                .HasComment("毕业院校")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_P_EmployeeTab_p_emp_graduatedschool");
            entity.Property(e => e.p_emp_happentime).HasComment("发生时间");
            entity.Property(e => e.p_emp_health)
                .HasDefaultValue("")
                .HasComment("健康状况")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_P_EmployeeTab_p_emp_health");
            entity.Property(e => e.p_emp_height)
                .HasDefaultValue("")
                .HasComment("身高")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_P_EmployeeTab_p_emp_height");
            entity.Property(e => e.p_emp_idaddress)
                .HasDefaultValue("")
                .HasComment("户籍详细地址")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_P_EmployeeTab_p_emp_idaddress");
            entity.Property(e => e.p_emp_idcardenddt).HasComment("身份证到期日");
            entity.Property(e => e.p_emp_idcardnum)
                .HasDefaultValue("")
                .HasComment("身份证号码")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_P_EmployeeTab_p_emp_idcardnum");
            entity.Property(e => e.p_emp_joindt).HasComment("入公司时间");
            entity.Property(e => e.p_emp_leaderid)
                .HasDefaultValueSql("((0))")
                .HasComment("直接上级领导姓名")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_P_EmployeeTab_p_emp_leaderid");
            entity.Property(e => e.p_emp_linkman1).HasComment("第一联系人");
            entity.Property(e => e.p_emp_linkphone)
                .HasDefaultValue("")
                .HasComment("联系电话")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_P_EmployeeTab_p_emp_linkphone");
            entity.Property(e => e.p_emp_linkphone1).HasComment("第一联系电话");
            entity.Property(e => e.p_emp_locality).HasComment("地区类型");
            entity.Property(e => e.p_emp_mapaddress)
                .HasDefaultValue("")
                .HasComment("地图坐标")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_P_EmployeeTab_p_emp_mapaddress");
            entity.Property(e => e.p_emp_marriedstatus)
                .HasDefaultValue("")
                .HasComment("婚姻状况")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_P_EmployeeTab_p_emp_marriedstatus");
            entity.Property(e => e.p_emp_minchat).HasComment("微信号");
            entity.Property(e => e.p_emp_minnumber).HasComment("短号");
            entity.Property(e => e.p_emp_nation)
                .HasDefaultValue("")
                .HasComment("民族")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_P_EmployeeTab_p_emp_nation");
            entity.Property(e => e.p_emp_nativeplace)
                .HasDefaultValue("")
                .HasComment("籍贯")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_P_EmployeeTab_p_emp_nativeplace");
            entity.Property(e => e.p_emp_no)
                .HasDefaultValue("")
                .HasComment("档案编号")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_P_EmployeeTab_p_emp_no");
            entity.Property(e => e.p_emp_operatedate).HasComment("操作时间");
            entity.Property(e => e.p_emp_operatorid).HasComment("操作员ID");
            entity.Property(e => e.p_emp_operatorname)
                .HasDefaultValue("")
                .HasComment("操作员名称")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_P_EmployeeTab_p_emp_operatorname");
            entity.Property(e => e.p_emp_othersalary)
                .HasDefaultValue(0.0)
                .HasComment("其它福利")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_P_EmployeeTab_p_emp_othersalary");
            entity.Property(e => e.p_emp_phone)
                .HasDefaultValue("")
                .HasComment("手机号码")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_P_EmployeeTab_p_emp_phone");
            entity.Property(e => e.p_emp_politicsstatus)
                .HasDefaultValue("")
                .HasComment("政治面貌\r\n")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_P_EmployeeTab_p_emp_politicsstatus");
            entity.Property(e => e.p_emp_positiveDate).HasComment("转正日期");
            entity.Property(e => e.p_emp_postid)
                .HasDefaultValueSql("((0))")
                .HasComment("岗位")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_P_EmployeeTab_p_emp_postid");
            entity.Property(e => e.p_emp_postion)
                .HasDefaultValue("")
                .HasComment("职位")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_P_EmployeeTab_p_emp_postion");
            entity.Property(e => e.p_emp_professionals)
                .HasDefaultValue("")
                .HasComment("专业")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_P_EmployeeTab_p_emp_professionals");
            entity.Property(e => e.p_emp_providerid)
                .HasDefaultValue(0)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_P_EmployeeTab_p_emp_providerid");
            entity.Property(e => e.p_emp_qq)
                .HasDefaultValue("")
                .HasComment("qq")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_P_EmployeeTab_p_emp_qq");
            entity.Property(e => e.p_emp_remotemedical).HasComment("异地就医申请日");
            entity.Property(e => e.p_emp_remotemedicaladdr)
                .HasDefaultValue("")
                .HasComment("异地就医所在地")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_P_EmployeeTab_p_emp_remotemedicaladdr");
            entity.Property(e => e.p_emp_retirementdt).HasComment("法定退休时间");
            entity.Property(e => e.p_emp_seclevel)
                .HasDefaultValueSql("((0))")
                .HasComment("安全级")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_P_EmployeeTab_p_emp_seclevel");
            entity.Property(e => e.p_emp_sex)
                .HasDefaultValue("")
                .HasComment("性别")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_P_EmployeeTab_p_emp_sex");
            entity.Property(e => e.p_emp_shortname)
                .HasDefaultValue("")
                .HasComment("简称")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_P_EmployeeTab_p_emp_shortname");
            entity.Property(e => e.p_emp_signid)
                .HasDefaultValue(0)
                .HasComment("标识字段")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_P_EmployeeTab_p_emp_signid");
            entity.Property(e => e.p_emp_socialadddt).HasComment("社保增加日期");
            entity.Property(e => e.p_emp_socialaddr)
                .HasDefaultValue("")
                .HasComment("社保所在地")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_P_EmployeeTab_p_emp_socialaddr");
            entity.Property(e => e.p_emp_sociallesdt).HasComment("社保减少日期");
            entity.Property(e => e.p_emp_socialnum)
                .HasDefaultValue("")
                .HasComment("社保个人编号")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_P_EmployeeTab_p_emp_socialnum");
            entity.Property(e => e.p_emp_status)
                .HasDefaultValue("")
                .HasComment("就职状态")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_P_EmployeeTab_p_emp_status");
            entity.Property(e => e.p_emp_stepOverName).HasComment("终审人员");
            entity.Property(e => e.p_emp_stepTime)
                .HasDefaultValue(0m)
                .HasComment("处理时限")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_P_EmployeeTab_p_emp_stepTime");
            entity.Property(e => e.p_emp_stepcode)
                .HasDefaultValue(0)
                .HasComment("步骤代码")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_P_EmployeeTab_p_emp_stepcode");
            entity.Property(e => e.p_emp_stepdirection)
                .IsFixedLength()
                .HasComment("流转方向");
            entity.Property(e => e.p_emp_stepover)
                .HasDefaultValue(0)
                .HasComment("终审标记")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_P_EmployeeTab_p_emp_stepover");
            entity.Property(e => e.p_emp_stepoverid)
                .HasDefaultValue(0)
                .HasComment("终审人ID")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_P_EmployeeTab_p_emp_stepoverid");
            entity.Property(e => e.p_emp_stepovertime).HasComment("终审时间");
            entity.Property(e => e.p_emp_temporaryNum).HasComment("暂住证号");
            entity.Property(e => e.p_emp_temporaryStrdate).HasComment("暂住开始");
            entity.Property(e => e.p_emp_temporaryenddate).HasComment("暂住结束");
            entity.Property(e => e.p_emp_tryenddt).HasComment("实际试用期满日");
            entity.Property(e => e.p_emp_trypenddt).HasComment("试用期结束日期");
            entity.Property(e => e.p_emp_trysdt).HasComment("试用期开始日期");
            entity.Property(e => e.p_emp_type)
                .HasComment("0,普通员工，1供应商员工，2客户员工")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__P_Employe__p_emp__15A7C802");
            entity.Property(e => e.p_emp_unionsNum).HasComment("工会会号");
            entity.Property(e => e.p_emp_wagesType).HasComment("工资类型");
            entity.Property(e => e.p_emp_weight)
                .HasDefaultValue("")
                .HasComment("体重")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_P_EmployeeTab_p_emp_weight");
            entity.Property(e => e.p_emp_zhijian).HasComment("员工直间属性");
            entity.Property(e => e.shigang)
                .HasDefaultValue(1)
                .HasAnnotation("Relational:DefaultConstraintName", "DF__P_Employe__shiga__12CB5B57");
            entity.Property(e => e.sign)
                .HasDefaultValue((short)0)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_P_EmployeeTab_sign");
            entity.Property(e => e.spcPurview)
                .HasDefaultValue("")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_P_EmployeeTab_spcPurview");
        });

        modelBuilder.Entity<Sys_FileRecord>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Sys_File__3214EC071B0D7E63");

            entity.Property(e => e.Id).HasDefaultValueSql("(newid())");
            entity.Property(e => e.UploadTime).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<mes_ProcessListTab>(entity =>
        {
            entity.ToTable(tb =>
                {
                    tb.HasTrigger("trg_PreventMesProcessDelete");
                    tb.HasTrigger("trg_PreventMesProcessInsert");
                    tb.HasTrigger("trg_PreventMesProcessModification");
                });

            entity.Property(e => e.mes_prolist_ProductId)
                .HasDefaultValue("")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Table_1_mes_pro_ProductId");
            entity.Property(e => e.mes_prolist_flid)
                .HasDefaultValue(0)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_mes_ProcessListTab_mes_prolist_flid");
            entity.Property(e => e.mes_prolist_gz1)
                .HasDefaultValue(0m)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_mes_ProcessListTab_mes_prolist_gz1");
            entity.Property(e => e.mes_prolist_gz2)
                .HasDefaultValue(0m)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_mes_ProcessListTab_mes_prolist_gz2");
            entity.Property(e => e.mes_prolist_gz3)
                .HasDefaultValue(0m)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_mes_ProcessListTab_mes_prolist_gz3");
            entity.Property(e => e.mes_prolist_gz4)
                .HasDefaultValue(0m)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_mes_ProcessListTab_mes_prolist_gz4");
            entity.Property(e => e.mes_prolist_gz5)
                .HasDefaultValue(0m)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_mes_ProcessListTab_mes_prolist_gz5");
            entity.Property(e => e.mes_prolist_int1)
                .HasDefaultValue(0)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_mes_ProcessListTab_mes_prolist_int1");
            entity.Property(e => e.mes_prolist_int2)
                .HasDefaultValue(0)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_mes_ProcessListTab_mes_prolist_int2");
            entity.Property(e => e.mes_prolist_int3)
                .HasDefaultValue(0)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_mes_ProcessListTab_mes_prolist_int3");
            entity.Property(e => e.mes_prolist_int4)
                .HasDefaultValue(0)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_mes_ProcessListTab_mes_prolist_int4");
            entity.Property(e => e.mes_prolist_int5)
                .HasDefaultValue(0)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_mes_ProcessListTab_mes_prolist_int5");
            entity.Property(e => e.mes_prolist_isHJ)
                .HasDefaultValue(0)
                .HasAnnotation("Relational:DefaultConstraintName", "DF__mes_Proce__mes_p__7A16849E");
            entity.Property(e => e.mes_prolist_manhour)
                .HasDefaultValue(0m)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_mes_ProcessListTab_mes_prolist_manhour");
            entity.Property(e => e.mes_prolist_str1)
                .HasDefaultValue("")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_mes_ProcessListTab_mes_prolist_str1");
            entity.Property(e => e.mes_prolist_str2)
                .HasDefaultValue("")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_mes_ProcessListTab_mes_prolist_str2");
            entity.Property(e => e.mes_prolist_str3)
                .HasDefaultValue("")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_mes_ProcessListTab_mes_prolist_str3");
            entity.Property(e => e.mes_prolist_str4)
                .HasDefaultValue("")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_mes_ProcessListTab_mes_prolist_str4");
            entity.Property(e => e.mes_prolist_str5)
                .HasDefaultValue("")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_mes_ProcessListTab_mes_prolist_str5");
            entity.Property(e => e.mes_prolist_wsid)
                .HasDefaultValue(0)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_mes_ProcessListTab_mes_prolist_wsid");
        });

        modelBuilder.Entity<mes_ProcessTab>(entity =>
        {
            entity.ToTable(tb => tb.HasTrigger("trg_mes_ProcessTab_del"));

            entity.Property(e => e.mes_pro_AffirmDate).HasComment("提交时间");
            entity.Property(e => e.mes_pro_Affirmer)
                .HasDefaultValue(0)
                .HasComment("提交人")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_mes_ProcessTab_mps_mpl_Affirmer");
            entity.Property(e => e.mes_pro_ProductDescrip)
                .HasDefaultValue("")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Table_1_ProductDescrip");
            entity.Property(e => e.mes_pro_ProductId)
                .HasDefaultValue("")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Table_1_ProductId");
            entity.Property(e => e.mes_pro_Productunitname)
                .HasDefaultValue("")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Table_1_Productunitname");
            entity.Property(e => e.mes_pro_appellation)
                .HasDefaultValue("")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Table_1_appellation");
            entity.Property(e => e.mes_pro_bak)
                .HasDefaultValue("")
                .HasComment("主单备注")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_mes_ProcessTab_mps_mpl_bak");
            entity.Property(e => e.mes_pro_ban)
                .HasDefaultValue(0)
                .HasComment("审批锁定")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_mes_ProcessTab_mps_mpl_ban");
            entity.Property(e => e.mes_pro_billdocument_id)
                .HasDefaultValue("")
                .HasComment("单据编号")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_mes_ProcessTab_mps_mpl_billdocument_id");
            entity.Property(e => e.mes_pro_billtype)
                .HasDefaultValue(0)
                .HasComment("流转类别")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_mes_ProcessTab_mps_mpl_billtype");
            entity.Property(e => e.mes_pro_cancelFlag)
                .HasDefaultValue(0)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_mes_ProcessTab_mps_mpl_cancelFlag");
            entity.Property(e => e.mes_pro_changedt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("变更时间")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_mes_ProcessTab_mps_mpl_changedt");
            entity.Property(e => e.mes_pro_changeid)
                .HasComment("变更人员")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_mes_ProcessTab_mps_mpl_changeid");
            entity.Property(e => e.mes_pro_delbak)
                .HasDefaultValue("")
                .HasComment("禁用说明")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_mes_ProcessTab_mps_mpl_delbak");
            entity.Property(e => e.mes_pro_deldt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("禁用时间")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_mes_ProcessTab_mps_mpl_deldt");
            entity.Property(e => e.mes_pro_delid)
                .HasComment("禁用标记")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_mes_ProcessTab_mps_mpl_delid");
            entity.Property(e => e.mes_pro_deloperatorid)
                .HasComment("删除人员")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_mes_ProcessTab_mps_mpl_deloperatorid");
            entity.Property(e => e.mes_pro_endtime).HasComment("结束时间");
            entity.Property(e => e.mes_pro_handcraftId)
                .HasDefaultValueSql("((0))")
                .HasComment("手工单号")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_mes_ProcessTab_mps_mpl_handcraftId");
            entity.Property(e => e.mes_pro_happentime).HasComment("发生时间");
            entity.Property(e => e.mes_pro_inoutspecies)
                .HasComment("单据类别")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_mes_ProcessTab_mps_mpl_inoutspecies");
            entity.Property(e => e.mes_pro_model)
                .HasDefaultValue("")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Table_1_model");
            entity.Property(e => e.mes_pro_operatorname)
                .HasDefaultValue("")
                .HasComment("操作员名称")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_mes_ProcessTab_mps_mpl_operatorname");
            entity.Property(e => e.mes_pro_rtagid)
                .HasComment("单据标识")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_mes_ProcessTab_mps_mpl_rtagid");
            entity.Property(e => e.mes_pro_spec)
                .HasDefaultValue("")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Table_1_spec");
            entity.Property(e => e.mes_pro_stepOverName).HasComment("终审人员");
            entity.Property(e => e.mes_pro_stepTime)
                .HasDefaultValue(0m)
                .HasComment("处理时限")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_mes_ProcessTab_mps_mpl_stepTime");
            entity.Property(e => e.mes_pro_stepcode)
                .HasDefaultValue(0)
                .HasComment("步骤代码")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_mes_ProcessTab_mps_mpl_stepcode");
            entity.Property(e => e.mes_pro_stepdirection)
                .IsFixedLength()
                .HasComment("流转方向");
            entity.Property(e => e.mes_pro_stepover)
                .HasDefaultValue(0)
                .HasComment("终审标记")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_mes_ProcessTab_mps_mpl_stepover");
            entity.Property(e => e.mes_pro_stepoverid)
                .HasDefaultValue(0)
                .HasComment("终审人ID")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_mes_ProcessTab_mps_mpl_stepoverid");
            entity.Property(e => e.mes_pro_stepovertime).HasComment("终审时间");
            entity.Property(e => e.mes_pro_wasteflag)
                .HasDefaultValue(0)
                .HasAnnotation("Relational:DefaultConstraintName", "DF__mes_Proce__mes_p__2696875F");
        });

        modelBuilder.Entity<mes_fl_listtab>(entity =>
        {
            entity.ToTable(tb => tb.HasComment("工艺表"));

            entity.Property(e => e.lskjimport_errorFlag).HasDefaultValue("0");
            entity.Property(e => e.mes_list_department).HasComment("");
            entity.Property(e => e.mes_list_eqb)
                .HasDefaultValue(0)
                .HasComment("E签宝");
            entity.Property(e => e.mes_list_mark).HasComment("");
            entity.Property(e => e.mes_list_name).HasComment("名称");
            entity.Property(e => e.mes_list_no).HasComment("");
            entity.Property(e => e.mes_list_operatedate).HasComment("");
            entity.Property(e => e.mes_list_operatorid).HasComment("");
            entity.Property(e => e.mes_list_wsid).HasComment("");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}