// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TunnelBackend.Features.Entities;

/// <summary>
/// 销售订单主表
/// </summary>
public partial class Crm_BillcoMaintab
{
    public int crm_mco_id { get; set; }

    /// <summary>
    /// 单据编号
    /// </summary>
    [Key]
    [StringLength(50)]
    [Unicode(false)]
    public string crm_mco_billdocument_id { get; set; }

    public int? crm_mco_groupid { get; set; }

    /// <summary>
    /// 结算客户
    /// </summary>
    public int? crm_mco_clientid { get; set; }

    /// <summary>
    /// 发货客户
    /// </summary>
    public int? crm_mco_shclientid { get; set; }

    /// <summary>
    /// 销售人员
    /// </summary>
    [StringLength(50)]
    [Unicode(false)]
    public string crm_mco_seller { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string crm_mco_SellerExe { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string crm_mco_SellerMgr { get; set; }

    /// <summary>
    /// 手工单号
    /// </summary>
    [StringLength(50)]
    [Unicode(false)]
    public string crm_mco_handcraftId { get; set; }

    /// <summary>
    /// 单据类别
    /// </summary>
    public int? crm_mco_inoutspecies { get; set; }

    /// <summary>
    /// 操作员ID
    /// </summary>
    public int? crm_mco_operatorid { get; set; }

    /// <summary>
    /// 操作时间
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? crm_mco_operatedate { get; set; }

    /// <summary>
    /// 流转类别
    /// </summary>
    public int? crm_mco_billtype { get; set; }

    /// <summary>
    /// 货币单位
    /// </summary>
    public int? crm_mco_currency { get; set; }

    [Column(TypeName = "decimal(18, 4)")]
    public decimal? crm_mco_exchangeRate { get; set; }

    public int? crm_mco_modeOfTrad { get; set; }

    /// <summary>
    /// 付款方式
    /// </summary>
    public int? crm_mco_payment { get; set; }

    public int? crm_mco_NwTradeTig { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string crm_mco_Transport { get; set; }

    /// <summary>
    /// 主单备注
    /// </summary>
    [StringLength(500)]
    [Unicode(false)]
    public string crm_mco_bak { get; set; }

    [StringLength(30)]
    [Unicode(false)]
    public string crm_mco_DistrictMgr { get; set; }

    /// <summary>
    /// 联系人员
    /// </summary>
    [StringLength(300)]
    [Unicode(false)]
    public string crm_mco_linkman { get; set; }

    /// <summary>
    /// 联系电话
    /// </summary>
    [StringLength(300)]
    [Unicode(false)]
    public string crm_mco_phone { get; set; }

    /// <summary>
    /// 送货地址
    /// </summary>
    [StringLength(300)]
    [Unicode(false)]
    public string crm_mco_address { get; set; }

    /// <summary>
    /// 发货方式
    /// </summary>
    public int? crm_mco_delivery { get; set; }

    /// <summary>
    /// 操作员名称
    /// </summary>
    [StringLength(10)]
    [Unicode(false)]
    public string crm_mco_operatorname { get; set; }

    /// <summary>
    /// 变更人员
    /// </summary>
    public int? crm_mco_changeid { get; set; }

    /// <summary>
    /// 变更时间
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? crm_mco_changedt { get; set; }

    /// <summary>
    /// 禁用标记
    /// </summary>
    public int? crm_mco_delid { get; set; }

    /// <summary>
    /// 禁用时间
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? crm_mco_deldt { get; set; }

    /// <summary>
    /// 删除人员
    /// </summary>
    public int? crm_mco_deloperatorid { get; set; }

    /// <summary>
    /// 禁用说明
    /// </summary>
    [StringLength(500)]
    [Unicode(false)]
    public string crm_mco_delbak { get; set; }

    /// <summary>
    /// 单据标识
    /// </summary>
    public int? crm_mco_rtagid { get; set; }

    /// <summary>
    /// 颜色标识
    /// </summary>
    [StringLength(50)]
    [Unicode(false)]
    public string crm_mco_colorid { get; set; }

    /// <summary>
    /// 提醒标识
    /// </summary>
    public int? crm_mco_automsgsign { get; set; }

    /// <summary>
    /// 提醒时间
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? crm_mco_automsgenddt { get; set; }

    /// <summary>
    /// 整单完成
    /// </summary>
    public int? crm_mco_mcomid { get; set; }

    /// <summary>
    /// 产品类别
    /// </summary>
    public int? crm_mco_pidtypeid { get; set; }

    /// <summary>
    /// 提交人
    /// </summary>
    public int? crm_mco_Affirmer { get; set; }

    /// <summary>
    /// 提交时间
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? crm_mco_AffirmDate { get; set; }

    /// <summary>
    /// 审批锁定
    /// </summary>
    public int? crm_mco_ban { get; set; }

    /// <summary>
    /// 步骤代码
    /// </summary>
    public int? crm_mco_stepcode { get; set; }

    /// <summary>
    /// 终审标记
    /// </summary>
    public int? crm_mco_stepover { get; set; }

    /// <summary>
    /// 发生时间
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? crm_mco_happentime { get; set; }

    /// <summary>
    /// 结束时间
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? crm_mco_endtime { get; set; }

    /// <summary>
    /// 流转方向
    /// </summary>
    [StringLength(1)]
    [Unicode(false)]
    public string crm_mco_stepdirection { get; set; }

    /// <summary>
    /// 终审时间
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? crm_mco_stepovertime { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? crm_mco_stepovertimeFirst { get; set; }

    /// <summary>
    /// 终审人ID
    /// </summary>
    public int? crm_mco_stepoverid { get; set; }

    /// <summary>
    /// 处理时限
    /// </summary>
    [Column(TypeName = "decimal(10, 2)")]
    public decimal? crm_mco_stepTime { get; set; }

    /// <summary>
    /// 终审人员
    /// </summary>
    [StringLength(30)]
    [Unicode(false)]
    public string crm_mco_stepOverName { get; set; }

    /// <summary>
    /// 订单类型
    /// </summary>
    public int? crm_mco_tagid { get; set; }

    /// <summary>
    /// 开票要求
    /// </summary>
    [StringLength(1000)]
    [Unicode(false)]
    public string crm_mco_requirements { get; set; }

    /// <summary>
    /// 相关单号
    /// </summary>
    [StringLength(5000)]
    [Unicode(false)]
    public string crm_mco_Related { get; set; }

    /// <summary>
    /// 打印次数
    /// </summary>
    public int? crm_mco_printCount { get; set; }

    /// <summary>
    /// 最后打印时间
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? crm_mco_printLastTime { get; set; }

    /// <summary>
    /// 最后打印人员
    /// </summary>
    public int? crm_mco_printLastOper { get; set; }

    /// <summary>
    /// 预览次数
    /// </summary>
    public int? crm_mco_previewCount { get; set; }

    /// <summary>
    /// 最后预览时间
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? crm_mco_previewLastTime { get; set; }

    /// <summary>
    /// 最后预览人员
    /// </summary>
    public int? crm_mco_previewLastOper { get; set; }

    /// <summary>
    /// 准备完成时间
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? crm_mco_complete { get; set; }

    /// <summary>
    /// 预留字符串1
    /// </summary>
    [StringLength(300)]
    [Unicode(false)]
    public string crm_mco_str1 { get; set; }

    /// <summary>
    /// 预留字符串2
    /// </summary>
    [StringLength(300)]
    [Unicode(false)]
    public string crm_mco_str2 { get; set; }

    /// <summary>
    /// 预留字符串3
    /// </summary>
    [StringLength(300)]
    [Unicode(false)]
    public string crm_mco_str3 { get; set; }

    /// <summary>
    /// 预留字符串4
    /// </summary>
    [StringLength(300)]
    [Unicode(false)]
    public string crm_mco_str4 { get; set; }

    /// <summary>
    /// 预留字符串5
    /// </summary>
    [StringLength(100)]
    [Unicode(false)]
    public string crm_mco_str5 { get; set; }

    /// <summary>
    /// 预留字符串6
    /// </summary>
    [StringLength(100)]
    [Unicode(false)]
    public string crm_mco_str6 { get; set; }

    /// <summary>
    /// 预留字符串7
    /// </summary>
    [StringLength(100)]
    [Unicode(false)]
    public string crm_mco_str7 { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string crm_mco_URGENT { get; set; }

    /// <summary>
    /// 项目编号
    /// </summary>
    [StringLength(100)]
    [Unicode(false)]
    public string crm_mco_itemno { get; set; }

    /// <summary>
    /// 已审步骤
    /// </summary>
    [StringLength(100)]
    [Unicode(false)]
    public string crm_mco_pStepCode { get; set; }

    /// <summary>
    /// 关闭标记
    /// </summary>
    public int? crm_mco_cancelFlag { get; set; }

    /// <summary>
    /// 关闭时间
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? crm_mco_cancelTime { get; set; }

    /// <summary>
    /// 关闭人员
    /// </summary>
    public int? crm_mco_cancelOper { get; set; }

    /// <summary>
    /// 货币类型
    /// </summary>
    [StringLength(40)]
    [Unicode(false)]
    public string crm_mco_currencytype { get; set; }

    /// <summary>
    /// 项目名称
    /// </summary>
    [StringLength(100)]
    [Unicode(false)]
    public string crm_mco_itemname { get; set; }

    /// <summary>
    /// 合同号
    /// </summary>
    [StringLength(50)]
    [Unicode(false)]
    public string crm_mco_contractno { get; set; }

    /// <summary>
    /// 预留日期1
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? crm_mco_date1 { get; set; }

    /// <summary>
    /// 预留日期2
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? crm_mco_date2 { get; set; }

    /// <summary>
    /// 预留日期3
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? crm_mco_date3 { get; set; }

    /// <summary>
    /// 预留日期4
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? crm_mco_date4 { get; set; }

    /// <summary>
    /// 预留日期5
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? crm_mco_date5 { get; set; }

    /// <summary>
    /// 预留日期6
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? crm_mco_date6 { get; set; }

    /// <summary>
    /// 预留日期7
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? crm_mco_date7 { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string crm_mco_zzjgdm { get; set; }

    public int? crm_mco_cn { get; set; }

    /// <summary>
    /// 预留整型字段1
    /// </summary>
    public int? crm_mco_int1 { get; set; }

    /// <summary>
    /// 预留整型字段2
    /// </summary>
    public int? crm_mco_int2 { get; set; }

    /// <summary>
    /// 图号
    /// </summary>
    [StringLength(100)]
    [Unicode(false)]
    public string crm_mco_snmark { get; set; }

    public int? crm_mco_wasteoper { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? crm_mco_wastetime { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string crm_mco_mstr1 { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string crm_mco_mstr2 { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string crm_mco_mstr3 { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string crm_mco_mstr4 { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string crm_mco_mstr5 { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string crm_mco_ocustomerid { get; set; }

    [StringLength(30)]
    [Unicode(false)]
    public string crm_mco_jszq { get; set; }

    public int? crm_mco_businessid { get; set; }

    public int? crm_mco_includeFreight { get; set; }

    public int? crm_mco_saletype { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? crm_mco_PostponeMoney { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string crm_mco_BillModuleID { get; set; }

    public int? crm_mco_LockTig { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? crm_mco_YFsummoney { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string crm_mco_ddbumen { get; set; }

    public int? crm_mco_jiajitig { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string crm_mco_receipt { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string crm_mco_flinkman { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string crm_mco_fphone { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string crm_mco_faddress { get; set; }

    [Column(TypeName = "decimal(18, 4)")]
    public decimal? crm_mco_issendvoucher { get; set; }

    [Column(TypeName = "decimal(18, 4)")]
    public decimal? crm_mco_ybfsummoney { get; set; }

    [Column(TypeName = "decimal(18, 4)")]
    public decimal? crm_mco_ybsummoney { get; set; }

    public int? khtype { get; set; }

    public int? adjust { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string crm_mco_jsxyno { get; set; }

    public int? crm_mco_jswhether { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string crm_mco_zlxyno { get; set; }

    public int? crm_mco_zlwhether { get; set; }

    public int? crm_mco_department { get; set; }

    public int? crm_mco_tiaok { get; set; }

    public int? crm_mco_paybalance { get; set; }

    public int? crm_mco_paybalancedays { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string crm_mco_Payment_Due_Date { get; set; }

    /// <summary>
    /// 初始结算周期
    /// </summary>
    [StringLength(20)]
    [Unicode(false)]
    public string crm_mco_settlementdays { get; set; }

    public int? crm_mco_fwwhether { get; set; }

    public int? crm_mco_whether { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string crm_mco_projectNo { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string divide_bill { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string crm_mco_OldSystemBill { get; set; }

    /// <summary>
    /// 传递生成后的单据号
    /// </summary>
    [StringLength(500)]
    [Unicode(false)]
    public string crm_mco_cdbillno { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? crm_mco_cddate { get; set; }

    /// <summary>
    /// 传递操作人
    /// </summary>
    [StringLength(500)]
    [Unicode(false)]
    public string crm_mco_cdop { get; set; }

    /// <summary>
    /// 传递账套
    /// </summary>
    [StringLength(500)]
    [Unicode(false)]
    public string crm_mco_cdzt { get; set; }
}