// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TunnelBackend.Features.Entities;

/// <summary>
/// 销售订单明细表
/// </summary>
[Index("crm_lco_comid", Name = "Crm_BillcoListtab_COMID")]
[Index("crm_lco_comid", "crm_lco_finish", Name = "Crm_BillcoListtab_COMID22")]
[Index("crm_lco_tm", Name = "Crm_BillcoListtab_tm")]
[Index("crm_lco_billdocument_id", Name = "IX_Crm_BillcoListtab")]
public partial class Crm_BillcoListtab
{
    [Key]
    public int crm_lco_id { get; set; }

    /// <summary>
    /// 单据编号
    /// </summary>
    [Required]
    [StringLength(20)]
    [Unicode(false)]
    public string crm_lco_billdocument_id { get; set; }

    /// <summary>
    /// 物料编码
    /// </summary>
    [Required]
    [StringLength(500)]
    [Unicode(false)]
    public string crm_lco_productid { get; set; }

    /// <summary>
    /// 数量
    /// </summary>
    [Column(TypeName = "decimal(18, 8)")]
    public decimal? crm_lco_amount { get; set; }

    [Column(TypeName = "decimal(18, 8)")]
    public decimal? crm_lco_fprice { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? crm_lco_fsummoney { get; set; }

    /// <summary>
    /// 单价
    /// </summary>
    [Column(TypeName = "decimal(21, 12)")]
    public decimal? crm_lco_price { get; set; }

    /// <summary>
    /// 金额
    /// </summary>
    [Column(TypeName = "decimal(18, 2)")]
    public decimal? crm_lco_summoney { get; set; }

    /// <summary>
    /// 不含税单价
    /// </summary>
    [Column(TypeName = "decimal(21, 12)")]
    public decimal? crm_lco_noprice { get; set; }

    /// <summary>
    /// 不含税金额
    /// </summary>
    [Column(TypeName = "decimal(18, 2)")]
    public decimal? crm_lco_nosummoney { get; set; }

    /// <summary>
    /// 税率
    /// </summary>
    [Column(TypeName = "decimal(18, 8)")]
    public decimal? crm_lco_taxRate { get; set; }

    /// <summary>
    /// 订单条码
    /// </summary>
    [StringLength(200)]
    [Unicode(false)]
    public string crm_lco_tm { get; set; }

    /// <summary>
    /// 要货时间
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? crm_lco_buytime { get; set; }

    /// <summary>
    /// 仓量库数
    /// </summary>
    [Column(TypeName = "decimal(18, 2)")]
    public decimal? crm_lco_storage { get; set; }

    public int? crm_lco_LockTig { get; set; }

    /// <summary>
    /// 结算客户
    /// </summary>
    public int? crm_lco_clientid { get; set; }

    public int? crm_lco_MrpBusinessID { get; set; }

    public int? crm_lco_workshopid { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string crm_lco_qtbak { get; set; }

    /// <summary>
    /// 明细备注
    /// </summary>
    [StringLength(1000)]
    [Unicode(false)]
    public string crm_lco_bak { get; set; }

    /// <summary>
    /// 产品名称
    /// </summary>
    [StringLength(500)]
    [Unicode(false)]
    public string crm_lco_appellation { get; set; }

    /// <summary>
    /// 辅助数量
    /// </summary>
    [Column(TypeName = "decimal(18, 8)")]
    public decimal? crm_lco_famount { get; set; }

    /// <summary>
    /// 成本单价
    /// </summary>
    [Column(TypeName = "decimal(18, 8)")]
    public decimal? crm_lco_bprice { get; set; }

    /// <summary>
    /// 成本金额
    /// </summary>
    [Column(TypeName = "decimal(18, 2)")]
    public decimal? crm_lco_bsummoney { get; set; }

    /// <summary>
    /// 税额
    /// </summary>
    [Column(TypeName = "decimal(18, 2)")]
    public decimal? crm_lco_taxsummoney { get; set; }

    /// <summary>
    /// 汇率
    /// </summary>
    [Column(TypeName = "decimal(18, 8)")]
    public decimal? crm_lco_exchangeRate { get; set; }

    /// <summary>
    /// 产品型号
    /// </summary>
    [StringLength(400)]
    [Unicode(false)]
    public string crm_lco_spec { get; set; }

    /// <summary>
    /// 产品规格
    /// </summary>
    [StringLength(400)]
    [Unicode(false)]
    public string crm_lco_model { get; set; }

    /// <summary>
    /// 产品单位
    /// </summary>
    [StringLength(20)]
    [Unicode(false)]
    public string crm_lco_productunit { get; set; }

    /// <summary>
    /// 销售计划
    /// </summary>
    public int? crm_lco_crmplanid { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string crm_lco_kftm { get; set; }

    /// <summary>
    /// 自定2
    /// </summary>
    [StringLength(500)]
    [Unicode(false)]
    public string crm_lco_str1 { get; set; }

    /// <summary>
    /// 自定3
    /// </summary>
    [StringLength(500)]
    [Unicode(false)]
    public string crm_lco_str2 { get; set; }

    /// <summary>
    /// 原单编号
    /// </summary>
    [StringLength(1000)]
    [Unicode(false)]
    public string crm_lco_sourcebillid { get; set; }

    /// <summary>
    /// 原单名称
    /// </summary>
    [StringLength(1000)]
    [Unicode(false)]
    public string crm_lco_sourcename { get; set; }

    /// <summary>
    /// 技术要求
    /// </summary>
    [StringLength(1000)]
    [Unicode(false)]
    public string crm_lco_technicalbak { get; set; }

    /// <summary>
    /// 包装要求
    /// </summary>
    [StringLength(1200)]
    [Unicode(false)]
    public string crm_lco_packingbak { get; set; }

    /// <summary>
    /// 标签要求
    /// </summary>
    [StringLength(1200)]
    [Unicode(false)]
    public string crm_lco_labelbak { get; set; }

    /// <summary>
    /// 其它要求
    /// </summary>
    [StringLength(500)]
    [Unicode(false)]
    public string crm_lco_anotherbak { get; set; }

    [Column(TypeName = "decimal(18, 8)")]
    public decimal? crm_lco_storageZd { get; set; }

    /// <summary>
    /// 发货完成
    /// </summary>
    public int? crm_lco_comid { get; set; }

    /// <summary>
    /// 发货完成人员
    /// </summary>
    [StringLength(20)]
    [Unicode(false)]
    public string crm_lco_comidname { get; set; }

    /// <summary>
    /// 入库完成
    /// </summary>
    public int? crm_lco_jcomid { get; set; }

    /// <summary>
    /// 入库完成人员
    /// </summary>
    [StringLength(20)]
    [Unicode(false)]
    public string crm_lco_jcomidname { get; set; }

    /// <summary>
    /// 品牌
    /// </summary>
    [StringLength(500)]
    [Unicode(false)]
    public string crm_lco_brand { get; set; }

    /// <summary>
    /// 综合属性
    /// </summary>
    [StringLength(5000)]
    [Unicode(false)]
    public string crm_lco_productdescrip { get; set; }

    [StringLength(1000)]
    [Unicode(false)]
    public string crm_lco_snmark { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? crm_lco_PlanDt { get; set; }

    /// <summary>
    /// 预排数量
    /// </summary>
    [Column(TypeName = "decimal(18, 8)")]
    public decimal? crm_lco_planamount { get; set; }

    /// <summary>
    /// 预计实现ID
    /// </summary>
    public int? crm_lco_expectid { get; set; }

    public int? crm_lco_lpoid { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string crm_lco_coname { get; set; }

    [Column(TypeName = "decimal(18, 8)")]
    public decimal? crm_lco_DJminamount { get; set; }

    [Column(TypeName = "decimal(18, 8)")]
    public decimal? crm_lco_DJmaxamount { get; set; }

    [Column(TypeName = "decimal(18, 8)")]
    public decimal? crm_lco_Orderminamount { get; set; }

    [Column(TypeName = "decimal(18, 8)")]
    public decimal? crm_lco_DJpirce { get; set; }

    /// <summary>
    /// 预留价格1
    /// </summary>
    [Column(TypeName = "decimal(18, 8)")]
    public decimal? crm_Lco_price1 { get; set; }

    /// <summary>
    /// 预留价格2
    /// </summary>
    [Column(TypeName = "decimal(18, 8)")]
    public decimal? crm_Lco_price2 { get; set; }

    /// <summary>
    /// 预留价格3
    /// </summary>
    [Column(TypeName = "decimal(18, 8)")]
    public decimal? crm_Lco_price3 { get; set; }

    /// <summary>
    /// 预留价格4
    /// </summary>
    [Column(TypeName = "decimal(18, 8)")]
    public decimal? crm_Lco_price4 { get; set; }

    /// <summary>
    /// 预留价格5
    /// </summary>
    [Column(TypeName = "decimal(18, 8)")]
    public decimal? crm_Lco_price5 { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Crm_lco_area { get; set; }

    public int? longamount { get; set; }

    public int? badamount { get; set; }

    public int? crm_lco_planid { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string crm_lco_planidoper { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? crm_lco_planidopdt { get; set; }

    /// <summary>
    /// 接收单位
    /// </summary>
    [StringLength(100)]
    [Unicode(false)]
    public string crm_lco_receiveunit { get; set; }

    /// <summary>
    /// 修改id
    /// </summary>
    public int? crm_lco_modifyid { get; set; }

    /// <summary>
    /// 仓库分解
    /// </summary>
    [Column(TypeName = "decimal(18, 8)")]
    public decimal? crm_lco_wmamount { get; set; }

    /// <summary>
    /// 外购分解
    /// </summary>
    [Column(TypeName = "decimal(18, 8)")]
    public decimal? crm_lco_scmamount { get; set; }

    /// <summary>
    /// 自产分解
    /// </summary>
    [Column(TypeName = "decimal(18, 2)")]
    public decimal? crm_lco_mrpamount { get; set; }

    /// <summary>
    /// 委外分解
    /// </summary>
    [Column(TypeName = "decimal(18, 8)")]
    public decimal? crm_lco_wwamount { get; set; }

    /// <summary>
    /// 分解说明
    /// </summary>
    [StringLength(1000)]
    [Unicode(false)]
    public string crm_lco_planbak { get; set; }

    public int? crm_lco_storehouseid { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string crm_lco_str3 { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string crm_lco_str4 { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string crm_lco_str5 { get; set; }

    /// <summary>
    /// 自定义6
    /// </summary>
    [StringLength(500)]
    [Unicode(false)]
    public string crm_lco_str6 { get; set; }

    /// <summary>
    /// 自定义7
    /// </summary>
    [StringLength(500)]
    [Unicode(false)]
    public string crm_lco_str7 { get; set; }

    /// <summary>
    /// 自定义8
    /// </summary>
    [StringLength(500)]
    [Unicode(false)]
    public string crm_lco_str8 { get; set; }

    /// <summary>
    /// 自定义9
    /// </summary>
    [StringLength(500)]
    [Unicode(false)]
    public string crm_lco_str9 { get; set; }

    /// <summary>
    /// 自定义10
    /// </summary>
    [StringLength(500)]
    [Unicode(false)]
    public string crm_lco_str10 { get; set; }

    /// <summary>
    /// 自定义11
    /// </summary>
    [StringLength(500)]
    [Unicode(false)]
    public string crm_lco_str11 { get; set; }

    /// <summary>
    /// 自定义12
    /// </summary>
    [StringLength(500)]
    [Unicode(false)]
    public string crm_lco_str12 { get; set; }

    public int? crm_lco_plancomid { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string crm_lco_plancomoper { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? crm_lco_plancomopdt { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string crm_lco_jdtag { get; set; }

    public int? crm_lco_lsidx_id { get; set; }

    [Column(TypeName = "decimal(18, 8)")]
    public decimal? crm_lco_qmssummoney { get; set; }

    public int? crm_lco_finish { get; set; }

    [Column(TypeName = "decimal(18, 8)")]
    public decimal? crm_lco_finishAmount { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? crm_lco_finishdate { get; set; }

    /// <summary>
    /// 仓库分解
    /// </summary>
    [Column(TypeName = "decimal(18, 8)")]
    public decimal? crm_lco_kyamount { get; set; }

    /// <summary>
    /// 仓库分解
    /// </summary>
    [Column(TypeName = "decimal(18, 8)")]
    public decimal? crm_lco_kcamount { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? crm_lco_comiddate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? crm_lco_completedate { get; set; }

    /// <summary>
    /// 发货客户
    /// </summary>
    public int? crm_lco_shclientid { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string crm_lco_lstr1 { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string crm_lco_lstr2 { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string crm_lco_lstr3 { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string crm_lco_lstr4 { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string crm_lco_lstr5 { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string crm_lco_isgift { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string crm_lco_isBackup { get; set; }

    public int? crm_lco_currency { get; set; }

    public int? crm_lco_MrpType { get; set; }

    [StringLength(300)]
    [Unicode(false)]
    public string crm_lco_address { get; set; }

    public int? crm_lco_ParametId { get; set; }

    public int? crm_lco_modeOfTrad { get; set; }

    [StringLength(30)]
    [Unicode(false)]
    public string crm_lco_dbtype { get; set; }

    [Column(TypeName = "decimal(18, 1)")]
    public decimal? crm_lco_width { get; set; }

    [Column(TypeName = "decimal(18, 1)")]
    public decimal? crm_lco_length { get; set; }

    [Column(TypeName = "decimal(18, 1)")]
    public decimal? crm_lco_xbamount { get; set; }

    public int? crm_lco_waitnotice { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string crm_lco_crmproductid { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string crm_lco_crmmodel { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string crm_lco_crmdanhao { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string crm_lco_YsProductid { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string crm_lco_updatebakoper { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? crm_lco_updatebakdate { get; set; }

    public int? crm_lco_piid { get; set; }

    public int? crm_lco_comid_bom { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string crm_lco_crmproductid2 { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string crm_lco_crmmodel2 { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string crm_lco_crmDescrip2 { get; set; }

    [Column(TypeName = "decimal(18, 8)")]
    public decimal? crm_lco_crmCKfprice2 { get; set; }

    public int? crm_lco_crmtype2 { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string crm_lco_crmnumneed2 { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string crm_lco_crmDYneed2 { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string crm_lco_crmYMname2 { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string crm_lco_crmYZname2 { get; set; }

    public int? crm_lco_tousuid { get; set; }

    public int? crm_lco_DyTig { get; set; }

    [Column(TypeName = "decimal(18, 8)")]
    public decimal? crm_lco_int1 { get; set; }

    [Column(TypeName = "decimal(18, 8)")]
    public decimal? crm_lco_LyAmount { get; set; }

    public int? crm_lco_bjid { get; set; }

    [StringLength(1000)]
    [Unicode(false)]
    public string crm_lco_bakfh { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string crm_lco_crmdescribe { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string crm_lco_crmappellation { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string crm_lco_crmspec { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string crm_lco_yfitemname { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? crm_lco_yunbaofei { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? crm_lco_fyunbaofei { get; set; }

    public int? crm_lco_qzr { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? crm_lco_qztime { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? crm_lco_modifydate { get; set; }

    public int? crm_lco_modifyoper { get; set; }

    [Column(TypeName = "decimal(18, 4)")]
    public decimal? crm_lco_Pricing { get; set; }

    [Column(TypeName = "decimal(18, 4)")]
    public decimal? crm_lco_minPricing { get; set; }

    [Column(TypeName = "decimal(18, 6)")]
    public decimal? crm_lco_lsPricing { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string crm_lco_productIdD { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Crm_lco_sn { get; set; }

    public DateOnly? crm_lco_askDate { get; set; }

    public int? crm_lco_bptID { get; set; }

    public int? crm_lco_mrpFXID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? crm_lco_realtime { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string crm_lco_itemno { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string crm_lco_jsxy { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string crm_lco_key { get; set; }

    public int? crm_lco_jhtig { get; set; }

    /// <summary>
    /// 项目经理
    /// </summary>
    [StringLength(50)]
    [Unicode(false)]
    public string crm_lco_project_manager { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string crm_lco_bomBillid { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string crm_lco_processBillid { get; set; }

    public int? crm_lco_bom_comid { get; set; }

    public int? crm_lco_gy_comid { get; set; }

    public int? crm_lco_sj_comid { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string crm_lco_processBillid2 { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string crm_lco_serial { get; set; }

    public int? crm_lco_bzwcId { get; set; }

    public int? Crm_lco_ifcancel { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string crm_lco_contractBS { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string crm_lco_contractKh { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string crm_lco_ProductSx { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? crm_lco_YfAmount { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? crm_lco_ScAmount { get; set; }

    public int? crm_lco_yftig { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string crm_lco_color { get; set; }

    [StringLength(8000)]
    [Unicode(false)]
    public string crm_lco_LsRemark { get; set; }

    [StringLength(1000)]
    [Unicode(false)]
    public string crm_lco_xmbak { get; set; }

    public int? crm_lco_gqTig { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string crm_lco_gqop { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? crm_lco_gqopdt { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string crm_lco_guidstr { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? crm_lco_sczq { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string crm_lco_RDitemno { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? crm_lco_ksdate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? crm_lco_endtime { get; set; }

    /// <summary>
    /// 传递生成后的单据号
    /// </summary>
    [StringLength(500)]
    [Unicode(false)]
    public string crm_lco_cdbillno { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? crm_lco_cddate { get; set; }

    /// <summary>
    /// 传递操作人
    /// </summary>
    [StringLength(500)]
    [Unicode(false)]
    public string crm_lco_cdop { get; set; }

    public int? crm_lco_cdid { get; set; }

    /// <summary>
    /// 传递的物料编码
    /// </summary>
    [StringLength(300)]
    [Unicode(false)]
    public string crm_lco_cdproductid { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string crm_lco_cdjsxy { get; set; }

    public int? crm_lco_gq { get; set; }
}