// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TunnelBackend.Features.Entities;

public partial class mes_ProcessTab
{
    [Key]
    public int mes_pro_id { get; set; }

    /// <summary>
    /// 单据编号
    /// </summary>
    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string mes_pro_billdocument_id { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string mes_pro_ProductId { get; set; }

    [Required]
    [StringLength(200)]
    [Unicode(false)]
    public string mes_pro_appellation { get; set; }

    [StringLength(1000)]
    [Unicode(false)]
    public string mes_pro_spec { get; set; }

    [Required]
    [StringLength(500)]
    [Unicode(false)]
    public string mes_pro_model { get; set; }

    [Required]
    [StringLength(30)]
    [Unicode(false)]
    public string mes_pro_Productunitname { get; set; }

    [Required]
    [StringLength(200)]
    [Unicode(false)]
    public string mes_pro_ProductDescrip { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string mes_pro_TechnicsName { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? mes_pro_Operatedate { get; set; }

    public int? mes_pro_Operatorid { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string mes_pro_Int4 { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string mes_pro_no { get; set; }

    /// <summary>
    /// 操作员名称
    /// </summary>
    [Required]
    [StringLength(10)]
    [Unicode(false)]
    public string mes_pro_operatorname { get; set; }

    /// <summary>
    /// 变更人员
    /// </summary>
    public int mes_pro_changeid { get; set; }

    /// <summary>
    /// 变更时间
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? mes_pro_changedt { get; set; }

    /// <summary>
    /// 禁用标记
    /// </summary>
    public int mes_pro_delid { get; set; }

    /// <summary>
    /// 禁用时间
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? mes_pro_deldt { get; set; }

    /// <summary>
    /// 删除人员
    /// </summary>
    public int mes_pro_deloperatorid { get; set; }

    /// <summary>
    /// 禁用说明
    /// </summary>
    [Required]
    [StringLength(500)]
    [Unicode(false)]
    public string mes_pro_delbak { get; set; }

    /// <summary>
    /// 单据标识
    /// </summary>
    public int mes_pro_rtagid { get; set; }

    /// <summary>
    /// 主单备注
    /// </summary>
    [StringLength(500)]
    [Unicode(false)]
    public string mes_pro_bak { get; set; }

    /// <summary>
    /// 提交人
    /// </summary>
    public int? mes_pro_Affirmer { get; set; }

    /// <summary>
    /// 提交时间
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? mes_pro_AffirmDate { get; set; }

    /// <summary>
    /// 审批锁定
    /// </summary>
    public int? mes_pro_ban { get; set; }

    /// <summary>
    /// 步骤代码
    /// </summary>
    public int? mes_pro_stepcode { get; set; }

    /// <summary>
    /// 流转类别
    /// </summary>
    public int? mes_pro_billtype { get; set; }

    /// <summary>
    /// 终审标记
    /// </summary>
    public int? mes_pro_stepover { get; set; }

    /// <summary>
    /// 发生时间
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? mes_pro_happentime { get; set; }

    /// <summary>
    /// 结束时间
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? mes_pro_endtime { get; set; }

    /// <summary>
    /// 流转方向
    /// </summary>
    [StringLength(1)]
    [Unicode(false)]
    public string mes_pro_stepdirection { get; set; }

    /// <summary>
    /// 终审时间
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? mes_pro_stepovertime { get; set; }

    /// <summary>
    /// 终审人ID
    /// </summary>
    public int? mes_pro_stepoverid { get; set; }

    /// <summary>
    /// 处理时限
    /// </summary>
    [Column(TypeName = "decimal(10, 2)")]
    public decimal? mes_pro_stepTime { get; set; }

    /// <summary>
    /// 终审人员
    /// </summary>
    [StringLength(30)]
    [Unicode(false)]
    public string mes_pro_stepOverName { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string mes_pro_pStepCode { get; set; }

    public int? mes_pro_cancelFlag { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? mes_pro_cancelTime { get; set; }

    public int? mes_pro_cancelOper { get; set; }

    /// <summary>
    /// 手工单号
    /// </summary>
    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string mes_pro_handcraftId { get; set; }

    /// <summary>
    /// 单据类别
    /// </summary>
    public int mes_pro_inoutspecies { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string mes_pro_TechnicsCode { get; set; }

    public int? mes_pro_wasteoper { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? mes_pro_wastetime { get; set; }

    public int? mes_pro_wasteflag { get; set; }

    public int? mes_pro_Workholdingsolution { get; set; }

    public int? mes_pro_numberamount { get; set; }
}