// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TunnelBackend.Features.Entities;

/// <summary>
/// 工艺表
/// </summary>
[Index("mes_list_name", Name = "IX_mes_fl_listtab")]
public partial class mes_fl_listtab
{
    [Key]
    public int mes_list_id { get; set; }

    /// <summary>
    /// 名称
    /// </summary>
    [StringLength(50)]
    [Unicode(false)]
    public string mes_list_name { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string mes_list_mark { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string mes_list_no { get; set; }

    public int? mes_list_operatorid { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? mes_list_operatedate { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string mes_list_department { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string mes_list_wsid { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string SpeciesNo { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string SpeciesName { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string operatorname { get; set; }

    public short? sign { get; set; }

    public int? mes_fl_int1 { get; set; }

    public int? mes_fl_int2 { get; set; }

    public int? mes_fl_int3 { get; set; }

    public int? mes_fl_int4 { get; set; }

    public int? mes_fl_int5 { get; set; }

    public int? mes_list_TMtype { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string lskjimport_errorFlag { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string mes_list_markjsyq { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string mes_list_markjscs { get; set; }

    [Column(TypeName = "decimal(18, 4)")]
    public decimal? mes_list_gxde { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string mes_list_bak { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string mes_list_mesName { get; set; }

    public int? mes_list_cxid { get; set; }

    public int? mes_list_wxgy { get; set; }

    public int? mes_list_orderid { get; set; }

    public int? mes_list_bmpid { get; set; }

    public int? mes_list_autoID { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string mes_lstr_bmpspeciesno { get; set; }

    [StringLength(1000)]
    [Unicode(false)]
    public string mes_lstr_PurviewList { get; set; }

    [StringLength(8000)]
    [Unicode(false)]
    public string mes_list_OpnameAll { get; set; }

    /// <summary>
    /// E签宝
    /// </summary>
    public int? mes_list_eqb { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? MCapacity { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? DateMCapacity { get; set; }

    public int? pamount { get; set; }

    public int? michamount { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? Capacityrate { get; set; }
}