// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TunnelBackend.Features.Entities;

[Index("mes_prolist_billdocument_id", "mes_prolist_ProductId", Name = "idx_mes_ProcessListTab_mes_prolist_billdocument_id")]
[Index("mes_prolist_cxid", Name = "idx_mes_ProcessListTab_mes_prolist_cxid")]
public partial class mes_ProcessListTab
{
    [Key]
    public int mes_prolist_id { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string mes_prolist_billdocument_id { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string mes_prolist_ProductId { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string mes_prolist_no { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string mes_prolist_Name { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string mes_prolist_mark { get; set; }

    public int? mes_prolist_department { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string mes_prolist_number { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? mes_prolist_manhour { get; set; }

    [StringLength(1500)]
    [Unicode(false)]
    public string mes_prolist_str1 { get; set; }

    [StringLength(1500)]
    [Unicode(false)]
    public string mes_prolist_str2 { get; set; }

    [StringLength(1500)]
    [Unicode(false)]
    public string mes_prolist_str3 { get; set; }

    [StringLength(1500)]
    [Unicode(false)]
    public string mes_prolist_str4 { get; set; }

    [StringLength(1500)]
    [Unicode(false)]
    public string mes_prolist_str5 { get; set; }

    public int? mes_prolist_int1 { get; set; }

    public int? mes_prolist_int2 { get; set; }

    public int? mes_prolist_int3 { get; set; }

    public int? mes_prolist_int4 { get; set; }

    public int? mes_prolist_int5 { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? mes_prolist_gz1 { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? mes_prolist_gz2 { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? mes_prolist_gz3 { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? mes_prolist_gz4 { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? mes_prolist_gz5 { get; set; }

    public int? mes_prolist_wsid { get; set; }

    public int? mes_prolist_flid { get; set; }

    public int? mes_prolist_lsidx_id { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string mes_prolist_pdmkey { get; set; }

    public int? mes_prolist_sfww { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string mes_prolist_fenlei { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string mes_prolist_cengji { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string mes_prolist_firstGx { get; set; }

    public int? mes_prolist_isHJ { get; set; }

    public int? mes_prolist_WpClassGroupid { get; set; }

    public int? mes_prolist_cxid { get; set; }

    public int? mes_prolist_isinspect { get; set; }

    public int? mes_prolist_isattachment { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string mes_prolist_gjxp { get; set; }

    [Column(TypeName = "decimal(18, 3)")]
    public decimal? mes_prolist_manhour01 { get; set; }

    [Column(TypeName = "decimal(18, 3)")]
    public decimal? mes_prolist_manhour02 { get; set; }

    public int? mes_prolist_Whsolution { get; set; }
}