// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TunnelBackend.Features.Entities;

/// <summary>
/// 员工表
/// </summary>
[Index("p_emp_no", Name = "NonClusteredIndex-20240320-212646", IsUnique = true)]
[Index("EmployeeName", Name = "NonClusteredIndex-20240320-212708", IsUnique = true)]
[Index("LoginAccount", Name = "NonClusteredIndex-20240320-212733", IsUnique = true)]
[Index("p_emp_no", Name = "P_EmployeeTab_node")]
public partial class P_EmployeeTab
{
    /// <summary>
    /// 人员ID
    /// </summary>
    [Key]
    public int employeeid { get; set; }

    /// <summary>
    /// 档案编号
    /// </summary>
    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string p_emp_no { get; set; }

    /// <summary>
    /// 员工工号
    /// </summary>
    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string LoginAccount { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string DutyInt { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string EmployeeName { get; set; }

    public int? Departmentid { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Password { get; set; }

    public int? UseFlag { get; set; }

    /// <summary>
    /// 变更人员ID
    /// </summary>
    public int? p_emp_changeid { get; set; }

    /// <summary>
    /// 变更时间
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? p_emp_changedt { get; set; }

    /// <summary>
    /// 禁用时间
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? p_emp_deldt { get; set; }

    /// <summary>
    /// 标识字段
    /// </summary>
    public int? p_emp_signid { get; set; }

    /// <summary>
    /// 性别
    /// </summary>
    [StringLength(20)]
    [Unicode(false)]
    public string p_emp_sex { get; set; }

    /// <summary>
    /// 民族
    /// </summary>
    [StringLength(20)]
    [Unicode(false)]
    public string p_emp_nation { get; set; }

    /// <summary>
    /// 出生日期
    /// 
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? p_emp_birthday { get; set; }

    /// <summary>
    /// 籍贯
    /// </summary>
    [StringLength(500)]
    [Unicode(false)]
    public string p_emp_nativeplace { get; set; }

    /// <summary>
    /// 政治面貌
    /// 
    /// </summary>
    [StringLength(30)]
    [Unicode(false)]
    public string p_emp_politicsstatus { get; set; }

    /// <summary>
    /// 婚姻状况
    /// </summary>
    [StringLength(30)]
    [Unicode(false)]
    public string p_emp_marriedstatus { get; set; }

    /// <summary>
    /// 健康状况
    /// </summary>
    [StringLength(30)]
    [Unicode(false)]
    public string p_emp_health { get; set; }

    /// <summary>
    /// 学历
    /// </summary>
    [StringLength(500)]
    [Unicode(false)]
    public string p_emp_degree { get; set; }

    /// <summary>
    /// 毕业院校
    /// </summary>
    [StringLength(200)]
    [Unicode(false)]
    public string p_emp_graduatedschool { get; set; }

    /// <summary>
    /// 专业
    /// </summary>
    [StringLength(200)]
    [Unicode(false)]
    public string p_emp_professionals { get; set; }

    /// <summary>
    /// 专业技术职务
    /// </summary>
    [StringLength(200)]
    [Unicode(false)]
    public string p_emp_duty { get; set; }

    /// <summary>
    /// 现居地址
    /// </summary>
    [StringLength(200)]
    [Unicode(false)]
    public string p_emp_address { get; set; }

    /// <summary>
    /// 邮箱地址
    /// 
    /// </summary>
    [StringLength(100)]
    [Unicode(false)]
    public string p_emp_email { get; set; }

    /// <summary>
    /// 联系传真
    /// 
    /// </summary>
    [StringLength(50)]
    [Unicode(false)]
    public string p_emp_fax { get; set; }

    /// <summary>
    /// qq
    /// </summary>
    [StringLength(50)]
    [Unicode(false)]
    public string p_emp_qq { get; set; }

    /// <summary>
    /// 地图坐标
    /// </summary>
    [StringLength(50)]
    [Unicode(false)]
    public string p_emp_mapaddress { get; set; }

    /// <summary>
    /// 身份证号码
    /// </summary>
    [StringLength(50)]
    [Unicode(false)]
    public string p_emp_idcardnum { get; set; }

    /// <summary>
    /// 身份证到期日
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? p_emp_idcardenddt { get; set; }

    /// <summary>
    /// 户籍详细地址
    /// </summary>
    [StringLength(100)]
    [Unicode(false)]
    public string p_emp_idaddress { get; set; }

    /// <summary>
    /// 身高
    /// </summary>
    [StringLength(100)]
    [Unicode(false)]
    public string p_emp_height { get; set; }

    /// <summary>
    /// 体重
    /// </summary>
    [StringLength(100)]
    [Unicode(false)]
    public string p_emp_weight { get; set; }

    /// <summary>
    /// 岗位
    /// </summary>
    [StringLength(100)]
    [Unicode(false)]
    public string p_emp_postid { get; set; }

    /// <summary>
    /// 区域
    /// </summary>
    [StringLength(100)]
    [Unicode(false)]
    public string p_emp_areaid { get; set; }

    /// <summary>
    /// 直接上级领导姓名
    /// </summary>
    [StringLength(100)]
    [Unicode(false)]
    public string p_emp_leaderid { get; set; }

    /// <summary>
    /// 安全级
    /// </summary>
    [StringLength(100)]
    [Unicode(false)]
    public string p_emp_seclevel { get; set; }

    /// <summary>
    /// 企业工龄
    /// </summary>
    public double? p_emp_businessage { get; set; }

    /// <summary>
    /// 就职状态
    /// </summary>
    [StringLength(20)]
    [Unicode(false)]
    public string p_emp_status { get; set; }

    /// <summary>
    /// 最后工作日
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? p_emp_endworkdt { get; set; }

    /// <summary>
    /// 入公司时间
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? p_emp_joindt { get; set; }

    /// <summary>
    /// 法定退休时间
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? p_emp_retirementdt { get; set; }

    /// <summary>
    /// 试用期开始日期
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? p_emp_trysdt { get; set; }

    /// <summary>
    /// 试用期结束日期
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? p_emp_trypenddt { get; set; }

    /// <summary>
    /// 实际试用期满日
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? p_emp_tryenddt { get; set; }

    /// <summary>
    /// 合同类型
    /// </summary>
    [StringLength(50)]
    [Unicode(false)]
    public string p_emp_contracttype { get; set; }

    /// <summary>
    /// 目前执行合同编号
    /// </summary>
    [StringLength(50)]
    [Unicode(false)]
    public string p_emp_contractno { get; set; }

    /// <summary>
    /// 第几次签订合同
    /// </summary>
    [StringLength(100)]
    [Unicode(false)]
    public string p_emp_contractcount { get; set; }

    /// <summary>
    /// 劳动合同起时间
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? p_emp_contractsdt { get; set; }

    /// <summary>
    /// 劳动合同止时间
    /// 
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? p_emp_contractplanedt { get; set; }

    /// <summary>
    /// 离退休时间
    /// 
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? p_emp_contractenddt { get; set; }

    /// <summary>
    /// 离职原因
    /// 
    /// </summary>
    [StringLength(5000)]
    [Unicode(false)]
    public string p_emp_contractendbak { get; set; }

    /// <summary>
    /// 被动离职的具体原因
    /// </summary>
    [StringLength(500)]
    [Unicode(false)]
    public string p_emp_contractendcontent { get; set; }

    /// <summary>
    /// 社保个人编号
    /// </summary>
    [StringLength(50)]
    [Unicode(false)]
    public string p_emp_socialnum { get; set; }

    /// <summary>
    /// 社保增加日期
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? p_emp_socialadddt { get; set; }

    /// <summary>
    /// 社保所在地
    /// </summary>
    [StringLength(50)]
    [Unicode(false)]
    public string p_emp_socialaddr { get; set; }

    /// <summary>
    /// 社保减少日期
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? p_emp_sociallesdt { get; set; }

    /// <summary>
    /// 商业险类型
    /// </summary>
    [StringLength(50)]
    [Unicode(false)]
    public string p_emp_businesstype { get; set; }

    /// <summary>
    /// 商业险增加日期
    /// 
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? p_emp_businessadddt { get; set; }

    /// <summary>
    /// 商业险增加方式
    /// </summary>
    [StringLength(50)]
    [Unicode(false)]
    public string p_emp_businessway { get; set; }

    /// <summary>
    /// 公积金个人编号
    /// </summary>
    [StringLength(50)]
    [Unicode(false)]
    public string p_emp_fundnum { get; set; }

    /// <summary>
    /// 公积金增加日期
    /// 
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? p_emp_fundadddt { get; set; }

    /// <summary>
    /// 异地就医所在地
    /// </summary>
    [StringLength(500)]
    [Unicode(false)]
    public string p_emp_remotemedicaladdr { get; set; }

    /// <summary>
    /// 异地就医申请日
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? p_emp_remotemedical { get; set; }

    /// <summary>
    /// 基本工资
    /// </summary>
    public double? p_emp_basesalary { get; set; }

    /// <summary>
    /// 其它福利
    /// </summary>
    public double? p_emp_othersalary { get; set; }

    [StringLength(2000)]
    [Unicode(false)]
    public string AuditPurview { get; set; }

    [StringLength(2000)]
    [Unicode(false)]
    public string AffirmPurview { get; set; }

    [StringLength(2000)]
    [Unicode(false)]
    public string DeletePurview { get; set; }

    [StringLength(2000)]
    [Unicode(false)]
    public string DepotPurview { get; set; }

    public short? sign { get; set; }

    [StringLength(2000)]
    [Unicode(false)]
    public string Purview { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string spcPurview { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string SpeciesNo { get; set; }

    public int? msgdt { get; set; }

    public int? UseFlag1 { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string DirectSuperior { get; set; }

    public short? SoftOpenMode { get; set; }

    /// <summary>
    /// 删除人员
    /// </summary>
    public int? p_emp_deloperatorid { get; set; }

    /// <summary>
    /// 简称
    /// </summary>
    [StringLength(200)]
    [Unicode(false)]
    public string p_emp_shortname { get; set; }

    /// <summary>
    /// 操作员ID
    /// </summary>
    public int? p_emp_operatorid { get; set; }

    /// <summary>
    /// 操作员名称
    /// </summary>
    [StringLength(10)]
    [Unicode(false)]
    public string p_emp_operatorname { get; set; }

    /// <summary>
    /// 操作时间
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? p_emp_operatedate { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string p_emp_updateName { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? p_emp_updateDate { get; set; }

    /// <summary>
    /// 禁用标识
    /// </summary>
    public int? p_emp_delid { get; set; }

    /// <summary>
    /// 禁用说明
    /// </summary>
    [StringLength(500)]
    [Unicode(false)]
    public string p_emp_delbak { get; set; }

    /// <summary>
    /// 颜色标识
    /// </summary>
    [StringLength(50)]
    [Unicode(false)]
    public string p_emp_colorid { get; set; }

    /// <summary>
    /// 提醒标识
    /// </summary>
    public int? p_emp_automsgsign { get; set; }

    /// <summary>
    /// 提醒时间
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? p_emp_automsgenddt { get; set; }

    /// <summary>
    /// 提交人
    /// </summary>
    public int? p_emp_Affirmer { get; set; }

    /// <summary>
    /// 提交时间
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? p_emp_AffirmDate { get; set; }

    /// <summary>
    /// 审批锁定
    /// </summary>
    public int? p_emp_ban { get; set; }

    /// <summary>
    /// 步骤代码
    /// </summary>
    public int? p_emp_stepcode { get; set; }

    /// <summary>
    /// 流转类别
    /// </summary>
    public int? p_emp_billtype { get; set; }

    /// <summary>
    /// 终审标记
    /// </summary>
    public int? p_emp_stepover { get; set; }

    /// <summary>
    /// 发生时间
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? p_emp_happentime { get; set; }

    /// <summary>
    /// 结束时间
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? p_emp_endtime { get; set; }

    /// <summary>
    /// 流转方向
    /// </summary>
    [StringLength(1)]
    [Unicode(false)]
    public string p_emp_stepdirection { get; set; }

    /// <summary>
    /// 终审时间
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? p_emp_stepovertime { get; set; }

    /// <summary>
    /// 终审人ID
    /// </summary>
    public int? p_emp_stepoverid { get; set; }

    /// <summary>
    /// 红蓝字单据
    /// </summary>
    public int? p_emp_Rtagid { get; set; }

    /// <summary>
    /// 处理时限
    /// </summary>
    [Column(TypeName = "decimal(10, 2)")]
    public decimal? p_emp_stepTime { get; set; }

    /// <summary>
    /// 终审人员
    /// </summary>
    [StringLength(30)]
    [Unicode(false)]
    public string p_emp_stepOverName { get; set; }

    /// <summary>
    /// 联系电话
    /// </summary>
    [StringLength(20)]
    [Unicode(false)]
    public string p_emp_linkphone { get; set; }

    /// <summary>
    /// 手机号码
    /// </summary>
    [StringLength(50)]
    [Unicode(false)]
    public string p_emp_phone { get; set; }

    /// <summary>
    /// 职位
    /// </summary>
    [StringLength(50)]
    [Unicode(false)]
    public string p_emp_postion { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string operatorname { get; set; }

    /// <summary>
    /// 第一联系人
    /// </summary>
    [StringLength(50)]
    [Unicode(false)]
    public string p_emp_linkman1 { get; set; }

    /// <summary>
    /// 第一联系电话
    /// </summary>
    [StringLength(50)]
    [Unicode(false)]
    public string p_emp_linkphone1 { get; set; }

    /// <summary>
    /// 短号
    /// </summary>
    [StringLength(50)]
    [Unicode(false)]
    public string p_emp_minnumber { get; set; }

    /// <summary>
    /// 微信号
    /// </summary>
    [StringLength(50)]
    [Unicode(false)]
    public string p_emp_minchat { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string p_emp_wxbh { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string p_emp_khyh { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string p_emp_ygkh { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string ScmPlanView { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string CrmPlanView { get; set; }

    [Column(TypeName = "image")]
    public byte[] bmp { get; set; }

    /// <summary>
    /// 财务分类
    /// </summary>
    [StringLength(50)]
    [Unicode(false)]
    public string p_emp_FinanceType { get; set; }

    /// <summary>
    /// 保密协议
    /// </summary>
    [StringLength(50)]
    [Unicode(false)]
    public string p_emp_SecretAgreement { get; set; }

    /// <summary>
    /// 工资类型
    /// </summary>
    [StringLength(50)]
    [Unicode(false)]
    public string p_emp_wagesType { get; set; }

    /// <summary>
    /// 户口类型
    /// </summary>
    [StringLength(50)]
    [Unicode(false)]
    public string p_emp_ResidenceType { get; set; }

    /// <summary>
    /// 工会会号
    /// </summary>
    [StringLength(50)]
    [Unicode(false)]
    public string p_emp_unionsNum { get; set; }

    /// <summary>
    /// 地区类型
    /// </summary>
    [StringLength(50)]
    [Unicode(false)]
    public string p_emp_locality { get; set; }

    /// <summary>
    /// 暂住证号
    /// </summary>
    [StringLength(50)]
    [Unicode(false)]
    public string p_emp_temporaryNum { get; set; }

    /// <summary>
    /// 转正日期
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? p_emp_positiveDate { get; set; }

    /// <summary>
    /// 暂住开始
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? p_emp_temporaryStrdate { get; set; }

    /// <summary>
    /// 暂住结束
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? p_emp_temporaryenddate { get; set; }

    /// <summary>
    /// 人员备注
    /// </summary>
    [StringLength(200)]
    [Unicode(false)]
    public string p_emp_Remark { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string p_emp_photo { get; set; }

    public int lookmsgid { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string p_emp_practice { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string SkinName { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string PrivatePhone { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string p_emp_htqx { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string p_emp_dgs { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string p_emp_cfaddress { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string p_emp_cgcnbook { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string p_emp_softwarebook { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string p_emp_savebook { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string p_emp_tdpeofession { get; set; }

    [Column(TypeName = "image")]
    public byte[] p_emp_ElectronicSignature { get; set; }

    public int? p_emp_age { get; set; }

    public int? p_emp_DisabilityTig { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string p_emp_DisabilityType { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string p_emp_DisabilityCard { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string str1 { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string str2 { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string str3 { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string str4 { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string p_emp_str29 { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string p_emp_str30 { get; set; }

    [StringLength(5000)]
    [Unicode(false)]
    public string p_emp_bak1 { get; set; }

    public int? shigang { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string p_emp_str27 { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? p_emp_date1 { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string p_emp_str28 { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string p_emp_area { get; set; }

    public int? SyncFlag { get; set; }

    [StringLength(5000)]
    [Unicode(false)]
    public string p_emp_areabak { get; set; }

    /// <summary>
    /// 员工直间属性
    /// </summary>
    [StringLength(50)]
    [Unicode(false)]
    public string p_emp_zhijian { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string p_emp_str1 { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string p_emp_str2 { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string p_emp_str3 { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string p_emp_str4 { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string p_emp_str5 { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string p_emp_str6 { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string p_emp_str7 { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string p_emp_str8 { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string p_emp_str9 { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string p_emp_str10 { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string p_emp_str11 { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string p_emp_str12 { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string p_emp_str13 { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string p_emp_str14 { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string p_emp_str15 { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string p_emp_str16 { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string p_emp_str17 { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string p_emp_str18 { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string p_emp_str19 { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string p_emp_str20 { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string p_emp_str21 { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string p_emp_str22 { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string p_emp_str23 { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string p_emp_str24 { get; set; }

    public int? groupid { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string p_emp_EmployeeName { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string p_emp_str25 { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string p_emp_str26 { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string BmpTest { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string P_Emp_zzjgdm { get; set; }

    [StringLength(1000)]
    [Unicode(false)]
    public string p_emp_bak { get; set; }

    [Column(TypeName = "image")]
    public byte[] signImg { get; set; }

    /// <summary>
    /// 0,普通员工，1供应商员工，2客户员工
    /// </summary>
    public int p_emp_type { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? p_emp_schoolcomdt { get; set; }

    public int msglookid { get; set; }

    [StringLength(10)]
    public string DD { get; set; }

    public int? p_emp_providerid { get; set; }

    public int? p_emp_CarTig { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? p_emp_GZnumid { get; set; }

    public int? p_emp_GZpertaxid { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string p_emp_GZstatus { get; set; }

    public int? p_emp_GZDepartmentid { get; set; }

    public int? p_emp_GZworktype { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? p_emp_GZworknum { get; set; }

    public int? p_emp_GZwagetype { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? p_emp_GZwagenum { get; set; }

    public int? p_emp_GZsocialtype { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? p_emp_GZnetworknum { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? p_emp_GZcpfnum { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string p_emp_GZempname { get; set; }

    public int? p_emp_GZresearchtype { get; set; }

    public int? p_emp_GZwageway { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? p_emp_GZhightempnum { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? p_emp_GZlifenum { get; set; }

    public int? p_emp_GZCCtig { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? p_emp_GZywfCCrate { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? p_emp_GZempCCrate { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? p_emp_GZwageoldnum { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string p_emp_idcardname { get; set; }

    public int? p_emp_GZDepartmentid02 { get; set; }

    public int? p_emp_GZDepartmentid03 { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? p_emp_GZwageeddnum { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string p_emp_Disabilitynum { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string openid_weixin { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string company_code_weixin { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string company_name_weixin { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? p_emp_quitdt { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string lskjimport_errorFlag { get; set; }

    public int? p_emp_clientid { get; set; }

    public int? p_emp_logintype { get; set; }

    public int? p_emp_PwdErrNum { get; set; }

    public bool? p_emp_PwdLocked { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? p_emp_PwdLockDate { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string p_emp_ddbumen { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string GTClientId { get; set; }

    [StringLength(8000)]
    [Unicode(false)]
    public string CTClientInfo { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string AppVer { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? OsLastLoginDate { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string LoginOsModel { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string LoginOsID { get; set; }

    public int? FieldServiceType { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string p_emp_units { get; set; }

    public int? p_emp_department { get; set; }

    [StringLength(1000)]
    [Unicode(false)]
    public string webbmp { get; set; }

    [StringLength(1000)]
    [Unicode(false)]
    public string leadership1 { get; set; }

    [StringLength(1000)]
    [Unicode(false)]
    public string p_emp_zhishuld { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string MacAdress { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string p_emp_DepManager1 { get; set; }

    public int? p_emp_groupid { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string ClientIp { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string email { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string AppIndex { get; set; }

    public int? p_emp_AttendanceTime { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string p_emp_gcsqy { get; set; }

    public int? p_emp_shangjiader { get; set; }

    public int? locationType { get; set; }

    public int? p_emp_developTig { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string p_emp_leader { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string p_emp_leader1 { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string p_emp_leader2 { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string p_emp_leader3 { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? SYStdate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? SYEddate { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string CarNum { get; set; }

    public int? P_emp_LockID { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string p_emp_office { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string p_emp_favorite { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string p_emp_specialty { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string p_emp_specialty1 { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string P_emp_OpenBank { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string P_emp_OpenBank1 { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string P_emp_Banknum { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string P_emp_Banknum1 { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string P_emp_wxnum { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string p_emp_otherNum { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? P_emp_workstdt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? P_emp_workJoindt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? P_emp_workdt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? p_emp_contractstdt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? p_emp_contracteddt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? P_emp_workOutdt { get; set; }

    public int? P_emp_WorkAgeAmount { get; set; }

    public int? P_emp_dpID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? P_emp_operatorDate { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string P_emp_LockopName { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? P_emp_LockDT { get; set; }

    public int? P_emp_BanID { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string p_emp_xzSpeciesNo { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string p_emp_workzt { get; set; }

    public int? XzjobLevel { get; set; }

    public int? XzsalaryLevel { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string p_emp_Authorizedperson { get; set; }

    public DateOnly? p_emp_beginwork { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? p_emp_holidaybalance { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? p_emp_lastholidaybalance { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? p_emp_txholidaybalance { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? p_emp_lasttxholidaybalance { get; set; }

    public int? P_emp_hktype { get; set; }

    public DateOnly? p_emp_contractenddtL { get; set; }

    public DateOnly? p_emp_rztagdt { get; set; }

    public int? Xzclass { get; set; }

    public int? WgAmount { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string p_emp_u8no { get; set; }

    public int? p_emp_adminXzlevel { get; set; }

    public int? p_emp_techXzlevel { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string p_emp_newkey { get; set; }

    public int? p_emp_addTag { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string p_emp_ergen { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string p_emp_phone1 { get; set; }

    public int? kqserverid { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string P_emp_disSb { get; set; }

    /// <summary>
    /// offer薪资
    /// </summary>
    [Column(TypeName = "decimal(18, 2)")]
    public decimal? P_emp_offerXz { get; set; }

    /// <summary>
    /// 非实习入职日期
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? P_emp_nzjRzDate { get; set; }

    /// <summary>
    /// 年终奖倍数
    /// </summary>
    [Column(TypeName = "decimal(10, 2)")]
    public decimal? P_emp_nzjBs { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string linkphone { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string error_msg { get; set; }

    public Guid? AvatarFileId { get; set; }
}