// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TunnelBackend.Features.Entities;

public partial class Sys_FileRecord
{
    [Key]
    public Guid Id { get; set; }

    [Required]
    [StringLength(255)]
    public string FileName { get; set; }

    [Required]
    [StringLength(255)]
    public string StoredFileName { get; set; }

    [StringLength(100)]
    public string ContentType { get; set; }

    public long FileSize { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UploadTime { get; set; }

    [StringLength(50)]
    public string UploaderId { get; set; }
}